### ISSUE TITLE
Linear algebra for tangent vectors

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#10]
There are two options to do linear algebra on tangent vectors:

1. Without broadcasting:
```julia
tv1 = 2*tv2 + tv3 - tv4 
```
2. With broadcasting:
```julia
tv1 .= 2.*tv2 .+ tv3 .- tv4 
```

The variant with broadcasting will generally be faster but more troublesome to implement (there will have to be custom broadcast rules as far as I understand this). Do we require both variants to work on all manifolds? I suspect the `MatrixManifold` proposal #8 could be extended with some default broadcasting rules to reduce the effort required to make wrapped tangent vectors that support broadcast arithmetic.

**Comment by kellertuer** [comment]
Very good idea, though I am not sure, which version I favour.

**Comment by sethaxen** [comment]
Is this issue still needed?

**Comment by mateuszbaran** [comment]
I think we could keep it open until the broadcasting/no broadcasting thing is documented. Something like "For the highest compatibility you should use non-broadcasted operations but some manifolds and representations support broadcasting. Refer to documentation of the manifold you are using to check for this".

This is, though, a part of a more general issue: how do we document which manifolds support which operations?

**Comment by kellertuer** [comment]
I was thinking anyways to extend the specific manifold documentaion `.md`s with more details, i.e. a general description and references as well as illustrations for manifolds before delving into the functions. That markdown could be used to also state this property.

We should maybe agree on a generic structure of such a markdown file to have that always in a certain place on these pages?

**Comment by mateuszbaran** [comment]
I think it would be nice if such information about supporting (or not) different features was automatically generated from our test set but it looks like a more long-term project.

**Comment by kellertuer** [comment]
While for examples in the docs there exists `Literate.jl`, I have not really a clue how tests could do that ;) The general description I wanted to do anyways, but right a table of features automatically would be really sweet.

**Comment by mateuszbaran** [comment]
There would have to be a config file that describes what manifolds support what, that is used both by the testset (to specify keyword arguments of `test_manifold`) and in `@eval` blocks in documentation of each manifold to generate a table with support information.

**Comment by mateuszbaran** [comment]
#336 and #339 implemented broadcasting for two tangent vector types so I think it's quite safe to assume it can be used. Probably only `_HyperbolicTangentTypes` need to be fixed?

**Comment by kellertuer** [comment]
Yes they still need broadcasting, but since they just encapsulate an array that should not be too difficult. I will check.

**Comment by kellertuer** [comment]
Oh just one further idea: We could make `TVector` an `<: AbstractVector`, what do you think? Then we should just be able to do this by implementing `getindex`/`setindex`/`size`. Or would that be bad since we also would have to introduce the `T` as a type for `TVector`? Would that be actually that bad?

**Comment by mateuszbaran** [comment]
> Yes they still need broadcasting, but since they just encapsulate an array that should not be too difficult. I will check.

Yes, that should just be a copy-paste of `UMTVector` broadcasting, changing struct name and changing field names in `copy` and `copyto!`.

> Oh just one further idea: We could make `TVector` an `<: AbstractVector`, what do you think? Then we should just be able to do this by implementing `getindex`/`setindex`/`size`. Or would that be bad since we also would have to introduce the `T` as a type for `TVector`? Would that be actually that bad?

I think that would be more confusing than helpful. Having a single element type is one problem, another one is having to provide linear indexing for any tangent vector. Furthermore, tangent vectors on for example SO(n) are matrices, not vectors.

**Comment by kellertuer** [comment]
> I think that would be more confusing than helpful. Having a single element type is one problem, another one is having to provide linear indexing for any tangent vector. Furthermore, tangent vectors on for example SO(n) are matrices, not vectors.

And if we declare them as ` <: AbstractArray`s, i.e. `Vector{T} <: AbstractArray{T}`? That might reduce the amount of implementation, I am just not sure its worth the change.

**Comment by mateuszbaran** [comment]
No, I really don't think it's worth it. Anyway, what would be the `size` of `UMVTVector`? I prefer to have `TVector` separate from `AbstractArray`.

**Comment by kellertuer** [comment]
The size of `UMVTVector` is a very reasonable point. Ok, makes it simpler, since we don‘t have to update ManifoldsBase

**Comment by kellertuer** [comment]
Is this then now resolved and can be closed?

**Comment by mateuszbaran** [comment]
Yes, right, I think it's solved.
