### ISSUE TITLE
Add the simplex

### ISSUE THREAD

**Issue by sethaxen** [JuliaManifolds/Manifolds.jl#103]
We should at least have the unit simplex, potentially also the general simplex

**Comment by kellertuer** [comment]
You mean the Fisher-Rao metric on the interior of the probability simplex like https://ipa.math.uni-heidelberg.de/dokuwiki/Papers/Astroem2016d.pdf section 2.1? I have to check a few more references, but yes that could and should definitely be done.

**Comment by sethaxen** [comment]
No, I wasn't proposing a particular choice of metric, per se. But I was proposing the unit/standard/probability simplex (see e.g. https://en.wikipedia.org/wiki/Simplex#The_standard_simplex). I have not had a chance to read the linked paper.

This particular manifold arises frequently in statistics, since points on the unit simplex are weight vectors that sum to 1, such as those in mixture models. I don't know how the general simplex is used.

**Comment by kellertuer** [comment]
If we implement this we should at least have a metric; but I also haven't had time to look at this closer – and would also first like to look at embeddings (and finish the logo and finish the abstract).

**Comment by kellertuer** [comment]
I read a little bit in the paper mentioned above, it's a metric for the relative interior of the simplex, so the boundary is excluded, but despite that they have nice formulae (though not that nicely organized/presented) for exp/log/inner/distance...

**Comment by kellertuer** [comment]
I don't like the choice here https://www.manopt.org/reference/manopt/manifolds/multinomial/multinomialfactory.html that much, they implement a projection onto tangent spaces (does the previuos one also have) but a fake one onto the real interior again and the metric is the one from the embedding, which I think is strange (also no exp/log). So I think it will boil down to the interior of the simplex, not the simplex.

**Comment by mateuszbaran** [comment]
"Simplex" may not be the greatest name for the discrete Fisher-Rao metric on the space of discrete probability distributions. And it's indeed only for the interior of the simplex, the definition of this metric assumes positive probabilities everywhere. Anyway, probably the simplest way to deal with the Fisher-Rao metric is by applying the square root and using a (scaled) sphere geometry... at least that's what I was doing in a very similar case.

**Comment by mateuszbaran** [comment]
Technically the boundary of a simplex transforms OK to the boundary of the non-negative orthant of a sphere so there may be a unique extension of the metric to the boundary (assuming we want to deal with manifolds with boundaries) but I didn't think about it too much.

**Comment by kellertuer** [comment]
Yes, the paper I mentioned earlier does the metric based on a rescaled sphere but provides explicit formulae, I haven't checked whether that works well with the boundary (manifolds with boundary would be interesting, but I don't see them soon).

Concerning the name, I wanted to go with `ProbabilitySimplex`.

**Comment by sethaxen** [comment]
Examples 2.2-2.4, 2.6 of [this paper](https://arxiv.org/abs/1301.6064) (by Julia's own Simon Byrne) covers the simplex, in particular the Fisher-Rao metric and its equivalence to the Euclidean metric on the sphere mapped to the Simplex via isometric embedding by identifying the simplex with the positive orthant of the sphere.
If I understand correctly, then given `ϕ: 𝕊^d → Δ^d, x ↦ x^2`, with left inverse `ϕ^{-1}: θ ↦ √θ`, and a point `p ∈ Δ^d` then the exponential map on `Δ^d` is `exp_p = ϕ ∘ exp_{ϕ^{-1}(p)} ∘ dϕ^{-1}`. Does that sound right?

I don't have strong opinions on the name and am fine with `ProbabilitySimplex`.

**Comment by kellertuer** [comment]
Hm, at first glance it looks quite similar to the paper I linked (they also derive formulae wrt to an isometry of the sphere), and they provide explicit formulae for exp/log/... but I am surprised, that the paper you mention includes the boundary. Haven't seen that before and have to take a closer look.

**Comment by sethaxen** [comment]
Good eye, yes it seems they do (and I note Wikipedia does as well). It would appear that the local metric is undefined exactly at the boundary, which makes me think that the simplex would only be Riemannian if it does not include the boundary. I think this would mainly be a problem if computing the exponential map/local metric from a base point at the boundary, but I'm not certain if other problems can arise.

I should note that when doing gradient-based sampling in statistical applications, the boundaries are not included.

**Comment by kellertuer** [comment]
Well wikipedia says it's an embedded manifold in R^n with corners. Then the boundary is fine and belongs to the manifold.
But with the local isometry to the sphere, I think, that's different. As I said, I will take a closer look, but I think your mentioned paper and the one I mentioned work on the same manifold with same metric, just that the one `\ge` should've been a `>`.
