### ISSUE TITLE
Naming Scheme for project() and embed()

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#121]
I noticed that I introduced a slight naming inconsistency with `EmbeddedManifolds`. Currently there are

* `project_point(M,p)` (and `project_point!(M, q, p)`) for points
* `project_tangent(M,p,X)` (and `project_tangent!(M, Y, p,X)`) for tangents

but the opposite direction is currently
* `embed(M,p)` (and `embed!(M, q, p)`) for points
* `embed(M,p,X)` (and `embed!(M, Y, p, X)`) for tangents.

How should we unify this? I think one could simplify the first to just a `project`(`!`)? The only argument I see against that is that `project(M,p,X)` for tangents and `project!(M,q,p)` for points are quite similar in writing and arguments but do quite different things.

What do you think?

**Comment by mateuszbaran** [comment]
This inconsistency doesn't bother me that much. We can drop `_point` and `_tangent` if you want, ambiguity is not that much of an issue since we have different naming conventions for points and tangent vectors. Also `isapprox` follows the same pattern.

**Comment by kellertuer** [comment]
Right, `isapprox` follows the same scheme, then I would prefer to drop `_point` and `_tangent` to be consistent with `embed`. Yes we are not completely consistent, but here we can easily introduce a consistency. I will do this when the current two PRs are done.
