### ISSUE TITLE
Identity crisis

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#122]
While working on #115 a number of problems with `Identity` were identified. Some were fixed but there are still unsolved method ambiguities, mostly in basis-related functions. They should be solved one way or another.

**Comment by kellertuer** [comment]
I think with storing the identity element internally this is resolved?

One could – in some cases with high-dimensional manifolds even think about refactoring the scheme a little bit and overwrite the access to `e.p` by a function that generates the element only when explicitly needed.

**Comment by mateuszbaran** [comment]
We still have a few ambiguities due to this but it's mostly solved now.

I think we can handle that optimization for high-dimensional manifolds once it becomes a problem 🙂 .
