### ISSUE TITLE
Should PowerMetric store a metric inside?

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#125]
I just wanted to write a small test for `det_local_metric` on a `MetricManifold{PowerManifold,PowerMetric}` , seee https://github.com/JuliaManifolds/Manifolds.jl/blob/161014340e55ef5cb1e9df00a28655209a18128a/src/manifolds/PowerManifold.jl#L240 and encountered a problem: The current version can't work, since the inner calls are never `MetricManifold`s.

In order for them to be, one has to create a `MatricManifold` of the powers internal `Manifold` and an according `Metric`.  But at that point we only have the `PowerMetric`. So I would like to propose to store a `Metric` inside the `PowerMetric` for exactely cases like this. What do you think? Like for the one manifold, one metric should be enough.

**Comment by mateuszbaran** [comment]
I think the idea here is that `PowerMetric` should only be applied to `PowerManifold` of a `MetricManifold`, so the metric is actually stored in `M.manifold`. But it's not a particularly well developed part of the library so I'm not sure if it's the right choice. And it's not properly documented anyway.

By the way we also have `ProductMetric` that works similarly.

**Comment by kellertuer** [comment]
Ah, then the implementation is the wrong way around, since its a Metric manifold of a power manifold.
Your way around one indeed does not have to store the metric, the way it is currently used (the other way around) I think one has to store the metric. Do we have a preferred way of using that? I would also document that choice when we have chosen something.

**Comment by mateuszbaran** [comment]
I haven't really used the metric manifold yet in practice so I'm not sure which way should be preferred. Wrapping a `MetricManifold` seems nice though. Actually it looks like there is not even one manifold with the `PowerMetric` created at the moment. It should probably be something like
```julia
M = MetricManifold(SymmetricPositiveDefinite(3), Manifolds.LinearAffineMetric())
PM = MetricManifold(PowerManifold(M, 100, 100), PowerMetric())
```
for the 100x100 power manifold of (SPD with linear affine metric) with the power metric. I think it looks OK.

**Comment by kellertuer** [comment]
For this way around several functions have to get the `Metric` that is powered, so this order requires the metric to be stored within `PowerMetric` which would anyways be my favourite way, since `Manifold` is also stored within the power manifold.

**Comment by mateuszbaran** [comment]
I don't have strong feelings about it either way, so I'm fine with your proposal as long as it will be consistent between `PowerMetric` and `ProductMetric`.

**Comment by kellertuer** [comment]
Ok, I feel better with the metric being stored like the manifold, so I will do that. And actually doing it the other way around is still possible then.

**Comment by sethaxen** [comment]
I think what you're proposing (storing a metric within a `ProductMetric`) is consistent with what we do with `InvariantMetric`. There, `InvariantMetric` converts/annotates an existing metric to an invariant one. In my mind, `ProductMetric` would store a bunch of metrics and be interpreted as the cartesian product of these.

**Comment by kellertuer** [comment]
At further makes metric and power (or metric and product) invariant: currently only the order `PowerManifold(MetricManifold(M))` is possibl, and this makes `MetricManifold(PowerManifold(M))` completely functional. I will do this as my next task then, since it's relatively easy to do.

**Comment by mateuszbaran** [comment]
I've started some work on this in this branch: https://github.com/JuliaManifolds/Manifolds.jl/tree/mbaran/improve-power-metric but I couldn't quite figure out how to modify the dispatch so it's not finished.
