### ISSUE TITLE
Add support for Lie group ODEs

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#128]
There is some work being done on Lie group ODEs in OrdinaryDiffEq.jl. We may want to provide some integration with it: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/1064 .

**Comment by mateuszbaran** [comment]
This is quite fun. The big issue is how does one introduce a vector field on a manifold M. In RKMK methods (ref: https://arxiv.org/pdf/1207.0069.pdf ) one does that by having a Lie group G acting on M (there are certain condition this action must satisfy). Then there is a function `f: M -> g` (where g is the Lie algebra of G) that defines this vector field through, roughly speaking, differentials of group actions associated with `f`. This `f` defines the differential equation, and then one expresses the solver in terms of the group exponential of g, group action of G on M and, in some cases, Lie bracket of g. There are also more complicated variants that require differentials of the exponential map and other things.

There are also Crouch and Grossman methods which I don't understand well enough yet. Ref: https://papers.rgrossman.com/journal-011.pdf .

**Comment by kellertuer** [comment]
Just a short side remark: The differential of the exponential map is (for symmetric manifolds where you know a diagonalising ONB of the curvature tensor) implemented in Manopt.jl.

**Comment by mateuszbaran** [comment]
Oh, cool :slightly_smiling_face: . What do you currently use it for? In case we needed it, I've also seen a nice algorithm for differential of the exponential map on matrix Lie groups.

**Comment by kellertuer** [comment]
Here‘s the reference: https://manoptjl.org/stable/functions/differentials.html#Manopt.differential_exp_argument-Tuple{AbstractManifold,Any,Any,Any} . I use them – or to be more precise the adjoint differential (which is algorithmically _very_ similar) https://manoptjl.org/stable/functions/adjointdifferentials.html#Manopt.adjoint_differential_exp_argument-Tuple{AbstractManifold,Any,Any,Any} to compute for example the adjoint differential of a Bezier curve with respect to ist control points. This is for example used to compute the gradient of the (discretised) acceleration of a Bezier curve with respect to the control points. Maybe I could write a tutorial / example for that. Wanted to try Pluto anyways these days.

**Comment by mateuszbaran** [comment]
[ManifoldDiffEq.jl](https://github.com/JuliaManifolds/ManifoldDiffEq.jl/) is now released so I think we can close this issue
