### ISSUE TITLE
Don't always deploy preview docs

### ISSUE THREAD

**Issue by sethaxen** [JuliaManifolds/Manifolds.jl#148]
Not every PR adds to the docs enough to warrant deploying a preview build. One reason we wouldn't want to always deploy PR docs is that it can substantially increase the repo size over time (see e.g. ).

It might be good to deactivate deploying preview docs by default but enable it to be turned on for specific PRs. One solution is to only deploy docs on PRs if a special label is set (see https://github.com/tkf/MyPlayground.jl/pull/28 for an implementation). Another would be if something like `[preview docs]` was included in the commit message.

**Comment by kellertuer** [comment]
I was thinking, we could also manually delete old PRs? That might not decrease the size, but avoid too much clutter.

I like the label solution, you can set that if there is a certain amount or some serious changes to the docs

**Comment by sethaxen** [comment]
> I was thinking, we could also manually delete old PRs? That might not decrease the size, but avoid too much clutter.

You mean delete old preview docs from `gh-pages`? Yes, I think we should do that anyways.

> I like the label solution, you can set that if there is a certain amount or some serious changes to the docs

Yeah, I like that if someone other than us submits a PR, we can mark it for building preview docs without needing to commit ourselves.

**Comment by kellertuer** [comment]
Exactly, as far as I read on slack, they currently just stay there.

Exactly, that's what I thought, one can even at one point decide: Oh, I wanted to check the docs.

**Comment by sethaxen** [comment]
With GitHub Actions, this looks straightforward to do with labels. With Travis, right now the only option is to trigger with text in the commit message: https://docs.travis-ci.com/user/conditions-v1#examples

**Comment by kellertuer** [comment]
Since we switched to GitHub Actions in between, do we want to activate doing the docs only when push-preview label is set? I like the idea.
