### ISSUE TITLE
Projective spaces

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#159]
Maybe we should add a `Projective space` page to the list of basic manifolds that explains that projective spaces should be represented by `Grassmann` with `k=1`? We could also add faster `exp!` and `log!` for that case.

**Comment by sethaxen** [comment]
That's a good idea, although to fully support projective spaces, e.g. for directional statistics, it might make more sense to do make it its own type. e.g. how `Sphere` is implemented separately from `Stiefel`. This would let us keep the usual notation, that is, `ProjectiveSpace(n, field=𝔽)` would be represented in `𝔽^{n+1}`, as opposed to `Grassmann(n, 1, field=𝔽)`, which is represented in `𝔽^{n}`

Now that I think of it, maybe `Stiefel` should have some `k=1` overloads that call the same functions for the `Sphere` where it's more efficient.

**Comment by mateuszbaran** [comment]
Yes, making projective spaces their own type may be even better.
