### ISSUE TITLE
uniform_distribution broken for Distributions@0.22.5

### ISSUE THREAD

**Issue by dahong67** [JuliaManifolds/Manifolds.jl#166]
Current implementations of `uniform_distribution` for `Stiefel` and `Grassmann` don't work when `Distributions.jl` is at version `0.22.5`. Didn't catch it until I added `Manifolds.jl` to a project that had an older version of `Distributions.jl` already!

MWE:
```julia
(temp) pkg> st
Status `~/Downloads/temp/Project.toml`
  [31c24e10] Distributions v0.22.5
  [1cead3c2] Manifolds v0.1.6

julia> using Manifolds; rand(uniform_distribution(Grassmann(10,2),zeros(10,2)))
ERROR: type ScalMat has no field chol
Stacktrace:
 [1] getproperty(::PDMats.ScalMat{Float64}, ::Symbol) at ./Base.jl:33
[...]
```

Seems to work on `0.22.6` and up, likely due to this change: https://github.com/JuliaStats/Distributions.jl/pull/1080

**Comment by mateuszbaran** [comment]
OK, I think we should just lower-bound `Distributions.jl` at 0.22.6 for the next release. Thanks for checking!

**Comment by sethaxen** [comment]
Yes thanks to semver, this shouldn't be a problem.
