### ISSUE TITLE
Easier access to power and product manifold points/tangents

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#167]
While currently porting Manopt, I noticed, that it might be nice to have easier access methods. As an example for something like

````julia
M = Stiefel(3,2)^(5,4)
````

and having `p` on the manifold, it would be nice to have something similar to `p[I]`, that we would do for arrays – especially independent of the internal representation (array or nested).

What do you think about overwriting `getindex` and similarly `setindex`?

I was thinking about something like
````julia
a = p[M,2,3]
p[M,3,3] = a
```` 
would be possible? For `PowerManifold`, I think that should be doable, for `Product` accessing more than one element might yield a slight problem with the reshaper?

* Is that too much of an abuse of the index-access notation?
* is that doable witth Julia? (I tried shortly but got lost in technical details).

What I would especially like, if such an access is independent of the structure (nested/array) for ease of use.

**Comment by mateuszbaran** [comment]
Using manifold as an index is an interesting idea. That should work, yes. I can add that.

**Comment by mateuszbaran** [comment]
Do you need `a = p[M,2,3]` only with integer indices or also with colon or vectors of indices? Colon should be doable but vectors of indices may be tricky.

**Comment by kellertuer** [comment]
I would say integers is enough.  If there's a lot of requests we can still extend it later.

The one thing I am not yet sure about is, what we can do, if `p` and `X` have different dimensions – but in general I still like the approach of slightly misusing `[]` for a power manifold.

**Comment by mateuszbaran** [comment]
OK. What do you mean by `X` here?

**Comment by kellertuer** [comment]
Oh, sorry, I meant if point `p` and tangent `X` have different array size representations; currrently we don't have that, but _if_ we might have to take that into account (but we could solve that by different representation sizes).

**Comment by mateuszbaran** [comment]
If we needed points and tangent vectors with different representation sizes then there would be much more to change.

**Comment by mateuszbaran** [comment]
I'll have to be a bit careful here to minimize the number of potential ambiguities in `getvector` and `setvector!`. But I think we should be OK.

**Comment by sethaxen** [comment]
I'm sure we can do this. My concern is I can't think of an example in all the packages I've seen where getindex takes elements that aren't indices or ranges of indices. This seems like a very nonstandard use of getindex, and perhaps a different function should be used.

**Comment by kellertuer** [comment]
That's why I think it's a little misusing the idea, but it is quite comfortable I think - it makes product manifolds really really usable.

**Comment by sethaxen** [comment]
I must be misunderstanding what this is intended for. What would this do that `submanifold_point` doesn't do?

**Comment by kellertuer** [comment]
You mean `sub manifold_component` and `sub manifold_components`? Do they have mutating versions that modify an entry?

Even when we would add that, I think the above proposal would be a little easier to use (and I hope not too much misusing the `[...]` notation.

**Comment by sethaxen** [comment]
> You mean `sub manifold_component` and `sub manifold_components`? Do they have mutating versions that modify an entry?

No, they don't, but we could add it. In general, I agree we should have short aliases for these long functions (hence the piping syntax and and the `Base.in` proposal), but those short aliases should only be overloads of base functions when they are consistent with their usual usage across the Julia ecosystem.

So e.g. I think we could define something like `getindex(M::Manifold, i...) = submanifold(M, i...)`.
We could also do something like `Component(M, p)[i...]`, which introduces a helper type for `setindex!` and `getindex`. This wouldn't be any more convenient for doing one indexing, but if you were doing it multiple times in a single function, then it would get almost as much convenience as what you're proposing.

To be fine with your proposed override of `getindex`, I'd need to see an example of it being used this way elsewhere.

**Comment by kellertuer** [comment]
That's why I am asking, whether that's too far off from the syntax. I haven't seen it either, but I feel its reasonable, since the addressing depends on the (power/product) manifold.

I am completely fine with writing first out own functions, especially one like your `component` sounds reasonable. Maybe that would already give me enough convenience.

I am fine with any result on `getindex`/`setindex!` – while I have the proposed variant as my favourite, I am ok with sticking to a global Julia usage.

**Comment by mateuszbaran** [comment]
I think the `Component` structure could actually be extended to all manifolds -- something like `FVector` but for points. We could then overload `getindex` and `setindex!` for that type.

**Comment by kellertuer** [comment]
That would just be `<:MPoint`? The one thing I fear is, that I will use that a lot and we decided originally to not necessarily typ points/vectors for performance reasons – and now we introduce them again?

**Comment by mateuszbaran** [comment]
Right now `<:MPoint` doesn't have a clear meaning. And, as I wrote, we already have optional wrapping for cases where disambiguation is necessary (although maybe we should look for another solution there? I don't know). Anyway, we already have `_read` and `_write` internally so it's just a matter of designing a neater interface. By the way, it shouldn't be necessary to provide `representation_size` in each call since most of the time it will be a cheap operation (I put it separately in `PowerManifold` just to be on the safe side).

> Edit: Besides this philosophical question – for a `PowerMPoint` of course, overloading `getindex` and `set index!` is easy, though the power point needs information about power representations and such (so it has to maybe store the manifold inside?).

What do you mean by `PowerMPoint`? Some new type?

**Comment by kellertuer** [comment]
As far as I understood, you meant to introduce a `PowerMPoint<:MPoint` to do the get/set index (using `_read`/`_write`maybe)? I am still not sure what's the best way to go here.

**Comment by mateuszbaran** [comment]
I thought about introducing a type similar to `FVector`, so it would be something like
```julia
struct MarkedMPoint{TM<:Manifold,TD} <: MPoint
    M::TM
    data::TD
end
```
that would work for any manifold, and then it would have overloaded `getindex` and `setindex!` for power and product manifolds.

I think the best next step is defining new functions that call `_read` and `_write` (something like `get_component(M::Manifold, p, idx...)` and `set_component!(M::Manifold, q, p, idx...)`) because even if we add a type like `MarkedMPoint`, `getindex` and `setindex!` defined for it would just call these functions.

**Comment by kellertuer** [comment]
yes, the get/set you propose are a good start

for the type, that would mean to implement _all_ manifold functions for this type, tee (basically unwrapping to its data field?) it might also slow down product/power things I fear? At least with that in mind I came to the initial proposal

**Comment by mateuszbaran** [comment]
Yes, that type would be slower and introduce more problems (like you wrote, for example having to implement all functions for it and resolve new ambiguities). I'll write these `get_component` and `set_component!` functions then.
