### ISSUE TITLE
(Is there a way to) remove intern imports with __?

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#173]
We currently have 3 functions that we import that are internal ones:

* `check_manifold_point__transparent`
* `exp!__intransparent`
* `inner__intransparent`

as imports that I am not that much in favour of. Especially for the `exp!__intransparent` it seems, that it is nowhere explicitly used but might be redefined in a macro, since commenting that import out breaks some tests.

I tried to replace the inner, which is used in `MetricManifold` as
````Julia
function inner__intransparent(M::MMT, p, X, Y) where {MMT<:MetricManifold}
````

by what I thought we made the macro for
````julia
@decorator_transparent_fallback :intransparent function inner(M::MetricManifold, p, X, Y)
````

but it seems not to work or one still needs to import the internal function.

Is there a way to avoid the imports and still being able to “overwrite” fallback cases? In the old version with the symbols, though not that efficient, I had hoped that was possible. Can it be made possible here? That would be very nice, since an enduser might not want to delve into such imports.

**Comment by kellertuer** [comment]
So the line change works that I proposed, which makes the code nicer, still the import seems to be necessary.

**Comment by mateuszbaran** [comment]
It's not great to have these imports, although it doesn't seem to be a particularly import-ant issue 😉 .

**Comment by kellertuer** [comment]
no its actually just style and if we move metric over it might even vanish? I just wanted to keep track of it.

**Comment by kellertuer** [comment]
I understood that in the current form that is not possible, so I will close this. Maybe if we find a way to model decorators without `__` functions, this might resolve automatically.
