### ISSUE TITLE
CompatHelper needs an ssh deploy key

### ISSUE THREAD

**Issue by sethaxen** [JuliaManifolds/Manifolds.jl#176]
For CompatHelper to trigger CI when it opens a PR (e.g. https://github.com/JuliaManifolds/Manifolds.jl/pull/175), it needs an ssh deploy key. 
See https://github.com/JuliaRegistries/TagBot#ssh-deploy-keys for an explanation.

**Comment by mateuszbaran** [comment]
OK, that could be useful.
