### ISSUE TITLE
Cleaning up the documentation menu

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#200]
The menu on the left hand side of our documentation is quite chaotic at the moment, we should make it more organized.

**Comment by kellertuer** [comment]
Maybe we could first look for a good organisation here?
I think it would be nice to have About and Contributim further up. What do you propose for the structure in order to be more organised?

**Comment by mateuszbaran** [comment]
> Maybe we could first look for a good organisation here?

Yes, that's what I've opened this issue for :slightly_smiling_face: .

> I think it would be nice to have About and Contributim further up. What do you propose for the structure in order to be more organised?

I don't know, many documentation sites don't even have such things in the menu. Documenter itself has Contributing but it's at the very bottom.

Among other things I feel like Statistics and Distributions shouldn't be at the top level and things under the Library item are somewhat arbitrarily selected.

**Comment by kellertuer** [comment]
Well what about the following

* Home
* ManifoldsBase
* How To
  * Tutorials... I hope to do a few soon...
* Manifolds
  * ..long list...
* $Name
  * Distributions
  * Statistics
  * ... further features, e.g. AD?
* Misc.
  * About
  * Contribute
  * Notation
* Library

I am not that much in favour of the current Library items. An Internal functions within Misc would be good. But what about the `Public` section? AD should go into $Name

and for $Name we need a good name - Features on Manifolds?

**Comment by mateuszbaran** [comment]
Look good. The public section could maybe be called "Utilities" and go to $Name? We could remove the "Library" section and move all items from there to $Name as well. Maybe @sethaxen would have some suggestions?

**Comment by kellertuer** [comment]
Calling "Public" "Utilities" is a good idea I think.

**Comment by sethaxen** [comment]
So I prefer `How to` be named something like `Examples`, because in principle sample scripts without much annotation could be in there in addition to more elaborate tutorials.

I can't think of a better name for $Name than Features on Manifolds.

**Comment by kellertuer** [comment]
I am fine with `Examples`, my idea with `How To` or `Get Started` was to get a reader pointed to the page with the tutorials in the sense that this is a point to directly get started. But `Examples` is fine with me.

Features on Manifolds (or just Features, since everything is on/with manifolds?) is a good idea.

**Comment by kellertuer** [comment]
We are currently missing `_jacobian` in the docs, see https://github.com/JuliaManifolds/Manifolds.jl/runs/917792384#step:4:151 – should I remove that line when revising the docs anyways?

**Comment by mateuszbaran** [comment]
You can but #202 changes this part of documentation anyway.

**Comment by kellertuer** [comment]
Ok, I might still just remove it to have the docs clean.
