### ISSUE TITLE
Model quotient manifolds.

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#205]
I would like to have an abstract embedding type where the manifold is obtained from the embedding by a quotient manifold.

It might be an idea to do this with just an embedding type, but I think it might be worthwhile to even introduce a subtype

`QuotientManifold <: Manifold`,
that for example could be parametrised by two manifolds (whole space, factor) for the case of a submersion.

**Comment by mateuszbaran** [comment]
Actually, what operations on quotient manifolds do you have in mind? Vertical/horizontal decomposition of tangent vectors? Some things that can be constructed using `optimal_alignment`?

**Comment by kellertuer** [comment]
My ideas are

* vertical / horizontal decomposition
* map (usually called pi) to the representations (if that's different, but like project it might be id)
* for all quotients adapt things like `isapprox` to use distance or decomposition above

I came to that idea when I just adapted one `is approx`, but have not yet the full list of features In mind. Still, I feel it might be beneficial similar to EmbeddedManifold.

**Comment by mateuszbaran** [comment]
I think `QuotientManifold <: AbstractEmbeddedManifold` would make sense, right?

About the map pi, would that be different from `project`?

`QuotientManifold` should probably hold the `AbstractGroupAction` that is used to define it. Generic `distance` and `isapprox` could then use `optimal_alignment`.

By the way, landmark manifolds may be a good playground for quotient manifolds.

**Comment by kellertuer** [comment]
For quotient manifolds that are submersions, you are right, they are both embedded and quotient, then `project` is the same as `pi`.
I am not 100% sure whether this is always the case for all quotient manifolds, but for this case `AbstractEmbedddManifold` makes sense and would be useful (using `project` for `pi`.

And yes, in general it should also know its `AbstractGroupAction`.

I haven't worked with landmark manifolds, just stumbled upon this with fixed rand manifolds, or others, where one has to quotient out the orthogonal group.

**Comment by kellertuer** [comment]
In #443 I decided to now call the projection `canonical_project` to avoid confusion with the projection from the embedding.

The `QuotientManifold therein does not yet know its `GroupAction`, but that could also be a trait (i.e. something we again assume to be implicitly known if not specified explicitly).

**Comment by mateuszbaran** [comment]
> _edit_: I will definitely model vertical and horizontal vectors in that PR, but I am not yet sure what to do with optimal alignment, since I have not yet read much about that (in Absil, Mahony, Sepulchre).

This book has quite a bit of examples of optimal alignment: https://link.springer.com/book/10.1007/978-1-4939-4020-2 .

> The `QuotientManifold therein does not yet know its `GroupAction`, but that could also be a trait (i.e. something we again assume to be implicitly known if not specified explicitly).

I think we could just have `get_quotient_action` function that gives the action (if the quotient is defined as orbits of a group action).

**Comment by kellertuer** [comment]
Thanks for the link I will check that then.

The function sounds good, exactly thats why IO started that now on the Grassmann branch, since it involves also finding these names and functions. Grassmann with projection actually has a quotient action / Lie Group

**Comment by kellertuer** [comment]
So I read a little bit about alignment and optimal alignment, to me that seems to be a concept more from shape manifolds which we do not cover yet? I am not sure what that is (nor how to compute it _at all_) for general quotient manifolds; even for Shape manifolds it seems quite involved, so for now I am not sure what that function would bring; sure we can define/provide a signature for that, but I do not see how to compute it.

For the Group Action and/or Lie group involved in the quotient – sure that should be included as we said.

**Comment by mateuszbaran** [comment]
The only generic way to compute the optimal alignment is, as far as I know, as an optimization problem. Only for some actions there are better explicit or better algorithms.

Let's leave the optimal alignment for now though, I can tackle that later.

**Comment by kellertuer** [comment]
resolved by #443.
