### ISSUE TITLE
Simplify embed/project (embed!/project!) for AbstractEmbeddedManifold

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#223]
While working on #216, we noticed that most probably embedding and projecting for `AbstractEmbeddedManifold`s can be provided with a default, such that quite some repeating lines as

````julia
embed!(M::SymmetricPositiveDefinite, q, p) = (q .= p)
embed!(M::SymmetricPositiveDefinite, Y, p, X) = (Y .= X)
````
(we have about 14 of those). If we assume (currently that's indeed always the case) that `AbstractEmbeddedManifold` refers to the fact that a manifold is represented in some embedding, these can be omitted if we provide

````julia
embed!(M::AbstractEmbeddedManifold, q, p) = (q .= p)
embed!(M::AbstractEmbeddedManifold, Y, p, X) = (Y .= X)
````

and similarly maybe for a few `project!`s, where I think one has to be a little more careful

The non-mutating ones are hopefully already ok, since allocation is the same size as input in these cases, which seems to be the default anyways.

I propose to test this in a PR here, introduce the new default, remove all unnecessary lines and if that works do a “siblings-PR” in ManifoldsBase to introduce the general definitions there.

**Comment by sethaxen** [comment]
Can we switch to using `copyto!` instead of broadcast? Their performance is the same, but I think more types will support the former than the latter.

**Comment by kellertuer** [comment]
Sure, did already exactly that in ManifoldsBase, the newest PR solving this adapts to that, too.
