### ISSUE TITLE
Vector transport for AbstractPowerManifolds (seen with Oblique)

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#226]
When using `Oblique` I noticed two problems

1. the `vector_transport_x` methods won't work directly, I would've expected that `ParallelTransport()` would work, since for the end user Oblique just looks like a manifold and not like a power manifold. Currently it only works if one uses `PowerVectorTransport(ParallelTransport())` and similarly for any other transport one would like to use.
What would be the best way to fix this (for `AbstractPowerManifolds`)?

So for example I would expect this to work
````julia
using Manifolds
M = Sphere(2)^2
p = [1.0 1.0; 0.0 0.0; 0.0 0.0]
X = [0.0 0.0; 1.0 1.0; 0.0 0.0]
q = [0.0 0.0; 1.0 1.0; 0.0 0.0]
Y = vector_transport_to(M,p,X,q, ParallelTransport())
````
does not work but both
````julia
Y = vector_transport_to(M,p,X,q)
Y = vector_transport_to(M,p,X,q, PowerVectorTransport(ParallelTransport()))
````

**Comment by mateuszbaran** [comment]
I don't remember the details but `PowerVectorTransport` was introduced to deal with some ambiguities: https://github.com/JuliaManifolds/Manifolds.jl/pull/177#discussion_r416662763 . As with all ambiguities, there are surely other ways to fix them (such as `@invoke_maker`) but IMO `PowerVectorTransport` is less ugly (though also less intuitive for users).

**Comment by kellertuer** [comment]
Yes, maybe bug is a little strongly phrased – I just stumbled on this with a student – and at first glance its not that intuitive; maybe I'll try to avoid the `PowerVectorTransport` for the abstract case at least. For Power itself I'd be fine with it.

**Comment by kellertuer** [comment]
I think a good solution might be to provide the methods for vector transport with the non-power methods for `Oblique`, too. I will try that when my current PRs are finished.

**Comment by mateuszbaran** [comment]
Sure, that looks like a good solution. If you just do that for `Oblique` there should be no ambiguities.
