### ISSUE TITLE
Dropping support for Julia 1.0

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#253]
At what point are we going to drop support for Julia 1.0? It looks like there are new issues https://github.com/JuliaManifolds/Manifolds.jl/pull/248#issuecomment-724010505 with the diffeq ecosystem that simply isn't maintained for old Julia versions.

Unfortunately, we can't really exclude diffeq tests on Julia 1.0 because we can't have different test dependencies for different versions of Julia.

**Comment by kellertuer** [comment]
I am fine with dropping that support as of now, though it would also be nice to have a long-term version within our range.

**Comment by kellertuer** [comment]
I tried a little bit to get recipes working with 1.0, but I was not able to get it to work. So I would propose to drop support for 1.0, though it is still a while until the next LTS is available.

**Comment by mateuszbaran** [comment]
We can always think about re-adding support for 1.0 if someone makes an issue about it.

**Comment by kellertuer** [comment]
We did this already.
