### ISSUE TITLE
relax cholesky for SymmetricPositiveDefinite()

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#254]
I am currently running quite often into cholesky falling with the error that the matrix is not hermitian; investigating, this usually means its off by 10 -^15.

I would like to relax this in SymmetricPositiveDefinite (LinearAffineMetric).

Which would be the way to go? I have two ideas

* A keyword argument for `distance`, `log` and `norm` for the default implementation. This might be tricky, since it means that any decorator needs to be extended to also handle kwargs
* A `cholesky_tol` and `cholesky_check` for the manifold, (note that the metric is the default metric)

or do you have other ideas?

**Comment by mateuszbaran** [comment]
I have a few ideas. We can either symmetrize/Hermitize the matrix before calling Cholesky decomposition or wrap matrices in `Symmetric` or `Hermitian` wrapper before calling `cholesky`. I don't really like the kwarg solution, it would cause too many issues. If you want we can also add checks for symmetry of the matrix before getting rid of numerical inaccuracies but that looks like something `ValidationManifold` is for.

**Comment by kellertuer** [comment]
Sure, the `kwargs` might introduce too much trouble, wrapping it in symmetric or hermitian might kill errors you actually make?
That's why I thought of adding that to the manifold as “these tolerances/checks are used within computations with this manifold”.

I don't want to do checks actually, I know my code is fine (up to a little more tolerance than zero, which `cholesky` has by default).

**Comment by mateuszbaran** [comment]
> wrapping it in symmetric or hermitian might kill errors you actually make?

Yes, wrapping in `Symmetric` or `Hermitian` actually disregards the part of a matrix below its diagonal.

**Comment by kellertuer** [comment]
Yes, sure.
So if you actually _do_ an error (not just a slight numerical inaccuracy like in my case) I would like to have the opportunity to test.

We can of course disable cholesky tests and document it as: If you want tests, use the `ValidatorManifold`, I would be fine with that, too.

**Comment by mateuszbaran** [comment]
OK, I'm fine with either way so pick what you like more :slightly_smiling_face: .

**Comment by kellertuer** [comment]
This was resolved by using `Symmetric` within Cholesky.

**Comment by sethaxen** [comment]
The docstring for `cholesky` recommends handling this by decorating with `Hermitian` or `Symmetric`: https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.cholesky

**Comment by kellertuer** [comment]
Yes, thanks for linking that; we were thinking about maybe moving back to using eigvals; but a small part of my code failing was also me doing the wrong things. Doing them correctly _and_ using Symmetric (or Hermitian) made it all work again.
