### ISSUE TITLE
Improve test suite organization

### ISSUE THREAD

**Issue by sethaxen** [JuliaManifolds/Manifolds.jl#259]
Currently if one of the test sets fails, the test suite does not run to completion. The way to fix this is to place all `include` statements within a giant `@testset`. The downside is that if you are then running in the REPL, you don't get instant feedback about when a test set completes. The way around this is to print a message upon include.

https://github.com/JuliaDiff/ChainRules.jl/pull/308 did a nice job of this, also printing out time taken to execute a testset.

**Comment by mateuszbaran** [comment]
> The way to fix this is to place all `include` statements within a giant `@testset`.

Well, there is one problem: Julia 1.0 doesn't allow type definitions within `@testset`. It's probably just another reason to consider https://github.com/JuliaManifolds/Manifolds.jl/issues/253 .

> [JuliaDiff/ChainRules.jl#308](https://github.com/JuliaDiff/ChainRules.jl/pull/308) did a nice job of this, also printing out time taken to execute a testset.

This looks quite nice. Currently I either run a single file or don't care that much about instant feedback so I think it's a good idea.

**Comment by kellertuer** [comment]
I also think, it's a good idea, both to drop support for 1.0 and to do this rework. It looks neat, what ChainRules does.
