### ISSUE TITLE
Get rid of PowerX

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#263]
I am would like to get rid of the
* PowerRetraction
* PowerVectorTransport
* InversePowerRetraction (we might currently miss to export this)

The reason is easy. When I wrote my newest algorithm, I used exp/log/parallel transport. All was easy to call and nicely working.
Yesterday I generalized that to use arbitrary retractions/inverse_retractions/vector_transports,
so now for the problem on a `PowerManifold` to properly work as before I generalized the code I have to explicitly state the keywords
```
        vector_transport_method = PowerVectorTransport(ParallelTransport()),
        retracttion_method = PowerRetraction(ExponentialRetraction()),
        inverse_retraction = InversePowerRetraction(LogarithmicInverseRetraction()),
```
in my algorithm, which I find not nice. Maybe like we do for Basis we can resolve this ambiguity for all 3 types explicitly, though that means to store a list of the types within?

**Comment by mateuszbaran** [comment]
I'd actually prefer to keep these and just make the non-wrapped variants also work without ambiguities, that's definitely possible. Do you need some help with that?

**Comment by kellertuer** [comment]
I have a good idea already, to introduce the concrete types for `PowerManifold` is what I actually want I think.

**Comment by kellertuer** [comment]
So my idea works in the sense of that there are no ambiguities anymore, but there seems to be something important I missed, since nearly all tests that involve these three in power now fail. I am not yet sure where to start, since the small ones before all the large tests suits actually do work.
