### ISSUE TITLE
Fixed Rank Matrices <: AbstractMatrix

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaManifolds/Manifolds.jl#269]
I recently [coded](https://github.com/mmikhasenko/LowRankMatrices.jl) Fixed Rank Matrices as <: AbstractMatrix,
and was wondering how much it repeats to what you have in this [package](https://juliahub.com/docs/Manifolds/H884l/0.4.0/manifolds/fixedrankmatrices.html#)?

**Comment by kellertuer** [comment]
Nice!
That depends a little bit on which metric you plan to impose on your matrices, but in general we currently use a 3-factor (from svd actually  representation, but we also overload `+`, `*` and so on, just that we use our `MPoint` as a super type for points on the manifold.

So with the representation you use the vectors that represent the rank-1 decomposition. Rght?
There us also much more ways to represent a low rank matrix, see for example the list [here](https://www.manopt.org/tutorial.html#manifolds), though I think on there the metric is always the same, but I did not yet check.

What are your goals with your package?

**Comment by mmikhasenko** [comment]
thanks for the comment and the reference.

> So with the representation you use the vectors that represent the rank-1 decomposition. Rght?

Exactly.

> What are your goals with your package?

The low-rank matrices appear in the angular analysis in particle physics. Essentially, it saves up memory and speeds up multiplication significantly. So actually these are the two things I need.

I would be very happy if I can do it with `Manifolds.jl`

**Comment by mateuszbaran** [comment]
At the moment there seems to be not that much overlap since we use different representations. About that `AbstractMatrix` subtyping, we currently follow what `LinearAlgebra` does, that is not making matrix factorizations `<:AbstractMatrix`. The main motivation seems to be that a lot of matrix operations can't be performed efficiently on factorizations. This may not be a good justification for some applications though but it's hard to tell without seeing what problems arise when such a type isn't `<:AbstractMatrix`.

**Comment by mmikhasenko** [comment]
thanks for the answers!

**Comment by kellertuer** [comment]
...you were quite fast in closing, let me state that: If you want, we could for example include your type as one possible representation of points on said manifold, once you have the functionality covered we would need for retractions for example. Feel free to give us a note then.

**Comment by mmikhasenko** [comment]
Ah, yes. That sounds very good

**Comment by mmikhasenko** [comment]
The only thing that I need is to create an object (representing the matrix) from a vector (rank-1) or two vectors (rank-2),
and be able to multiply it from the left and right.

**Comment by kellertuer** [comment]
Ok, we might need a little more for our manifold, but I also haven't had time to look at other representations (as mentioned, there are a few.

**Comment by kellertuer** [comment]
I will close this due to inactivity. We can still talk about an implementation of the FixedRankMatrices functions with your representation if that becomes of interest for someone :)
