### ISSUE TITLE
Link to zenodo

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#273]
I tried to (first Manopt) link our repos to zenodo to get DOIs for all our version, but somehow when I activate it and there comes a new relese, afterwards its not activated no more. It also does not show up in out third party access things... Can someone else help/try?

**Comment by kellertuer** [comment]
I think our third party access is too restrictive. For the next release I will relax that and try (fist with Manopt, then here?).

**Comment by kellertuer** [comment]
It works and we have a DOI (see updated Readme). And I hopefully adapted the metadata.

I will try to restrict here again and look at the next release. It still seems to work with restrictions for the org (I noticed with Manopt.jl), since the web hooks are still activated.

**Comment by mateuszbaran** [comment]
Thanks for figuring it out :slightly_smiling_face: .
