### ISSUE TITLE
Support Euclidean() to be similar to PositiveNumbers()

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#327]
I just started playing around with mutating functions in Manopt and noticed, I will have to make a few special variants for `Circle()` and `ProsiviteNumbers()` since they work on `Float`s and hence can not have mutating gradient functions – or do not have a `retract!` for example.

I noticed that `Euclidean` can be initialised as `Euclidean()` though that currently does not make much sense.
Would it be reasonable to say that `Euclidean()` is the real numbers (i.e. providing a `Float` based implementation similar to the `PositiveNumers()`) and the 1-element-arrays are `Euclidean(1)` ?

**Comment by mateuszbaran** [comment]
I think ideally `Euclidean` should be able to work on plain numbers, `Ref`s to numbers and any 1-element arrays. I think it's doable but may require some fighting with ambiguities.
