### ISSUE TITLE
`NLsolveInverseRetraction` is not in documentation

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#343]
Currently the docstring for `NLsolveInverseRetraction` is not in out documentation (but it's linked in one place so the link is broken).

**Comment by mateuszbaran** [comment]
I don't even have a good idea where to put it.

**Comment by kellertuer** [comment]
Currently we usually put retractions near the manifolds where they are used (for example the https://juliamanifolds.github.io/Manifolds.jl/latest/manifolds/stiefel.html#Manifolds.CayleyRetraction ) does that maybe help? Otherwise we could also start to collect these types at a central place, maybe.

**Comment by mateuszbaran** [comment]
This inverse retraction could actually be used for multiple manifolds.

**Comment by kellertuer** [comment]
My second suggestion is, to have a common place for those, though I am not yet sure how to call that and where to put it, since it would be quite similar to the interface page. But it could also be moved to `ManifoldsBase`, then?

**Comment by mateuszbaran** [comment]
Yes, we could move it to `ManifoldsBase` and put it in the interface page.

**Comment by kellertuer** [comment]
This is resolved by JuliaManifolds/ManifoldsBase.jl#69 and #359.
