### ISSUE TITLE
Rename SkewSymmetricMatrices to SkewHermitianMatrices

### ISSUE THREAD

**Issue by sethaxen** [JuliaManifolds/Manifolds.jl#346]
I see that `SkewSymmetricMatrices` actually represents potentially complex skew-Hermitian points. Since complex skew-symmetric matrices can also be a manifold, we should rename it to `SkewHermitianMatrices`. Until we add a manifold for actually skew-symmetric matrices, we can have the alias `SkewSymmetricMatrices(n)=SkewHermitianMatrices(n,ℝ)`.

We can also forward to its projections and point checking, etc for the Lie algebras of `Unitary` and its subgroups.

**Comment by kellertuer** [comment]
I think it should even be fine to just have the alias. Why would you add it “actually” (again)?

**Comment by sethaxen** [comment]
Ah, I have no need for complex skew-symmetric matrices, but in principle one might. I'm just saying that if one ever wants to add that manifold, they could, and then the alias would just be removed.

**Comment by kellertuer** [comment]
Ah, then I misread your post, but sure. For now the alias should be enough to have a non-breaking change.

**Comment by sethaxen** [comment]
> For now the alias should be enough to have a non-breaking change.

I believe the proposed alias would still be a breaking change, because a user could have started using `SkewSymmetricMatrices(n, ℂ)`, which would no longer exist. I don't see a problem with making a minor release dropping that no-longer-supported constructor, but another option is to declare
```julia
const SkewSymmetricMatrices{n} = SkewHermitianMatrices{n,ℝ}
SkewSymmetricMatrices(n) = SkewHermitianMatrices{n,ℝ}()
@deprecate SkewSymmetricMatrices(n, 𝔽) SkewHermitianMatrices(n, 𝔽)
```
which would still have the same functionality but would raise a deprecation warning if the user tried to create a complex `SkewSymmetricMatrices` manifold. Then we could remove it whenever we next bump the minor version number, leaving only the real alias.

**Comment by kellertuer** [comment]
That's a very good idea.

**Comment by mateuszbaran** [comment]
That is a good change. Deprecation warning would be a good idea, and then it could be dropped in Manifolds.jl 0.5 (probably to be released after atlases are merged).
