### ISSUE TITLE
is_manifold_point (check_manifold_point) broken for semi direct product groups

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#349]
I noticed, that the checking of manifold points does not seem to work for semi direct product groups.

Here's an example.

```
julia> using Manifolds, Manopt

julia> M = SpecialEuclidean(3)
SpecialEuclidean(3)

julia> P = 1
1

julia> is_point(M,P)
true
```

I would have expected an implementation that checks both product parts somewhere? I think when we designed `check_point` it by default returns nothing, such that the is_manifold_point returns true then, so this implementation seems to be missing.

**Comment by kellertuer** [comment]
I think I figured this one out. The question is, whether we should do something about this.

What I thought was, that the transparency of `is_point` is wrong, but what actually happens:
1) `is_point` works for the group manifold, that is an `AbstractGroupManifold` which is an `AbstractEmbeddedManifold`.
2) hence `get_embedding` calls `decorated_manifold` which undecorates the group manifold and returns the inner product manifold
(this seems to be a little longish since with the correct transprarency a group manifold could directly dispatch this on its inner manifold, but ok).
3) so with `N` the inner product manifold `check_point(N,P)` is called
4) since the function call in 3 for a product manifold is only defined if `P` is a `ProductRepr` this goes up to the very generic `check_point(::AbstractManifold,p)` case which (with our lazy approach in mind) returns nothing.


So concerning 2) I feel a little strange that a group manifold is an abstract embedded manifold, I would have thought it is a decorator sure, but more like the metric manifold (where for sure the current path spares quite a few transparency rules to be defined) - so while a lazy less code approach here is nice, maybe we want to avoid that all group manifolds are embedded manifolds?
To avoid as many definitions as we do in Metric manifold, one could introduce a `Transparency Level` or `TransparencyType` already for the decorator level (similar as we do for embedded manifolds) to avoid lengthy transparency definitions as we currently have in metric manifold.

Concerning 4) Maybe we could introduce an error for `check_point(::ProductManifold, p)` when `p` is not a `ProductRepr` that it is of the wrong form? Or at least if it is neither a `ProductRepr` nor a `Tuple`? What do you think @mateuszbaran?

**Comment by mateuszbaran** [comment]
> So concerning 2) I feel a little strange that a group manifold is an abstract embedded manifold, I would have thought it is a decorator sure, but more like the metric manifold (where for sure the current path spares quite a few transparency rules to be defined) - so while a lazy less code approach here is nice, maybe we want to avoid that all group manifolds are embedded manifolds?
> To avoid as many definitions as we do in Metric manifold, one could introduce a `Transparency Level` or `TransparencyType` already for the decorator level (similar as we do for embedded manifolds) to avoid lengthy transparency definitions as we currently have in metric manifold.

Yes, sure, putting forwarding types directly in decorator seems to be a better idea than making `AbstractGroupManifold` embedded.

> Concerning 4) Maybe we could introduce an error for `check_point(::ProductManifold, p)` when `p` is not a `ProductRepr` that it is of the wrong form? Or at least if it is neither a `ProductRepr` nor a `Tuple`? What do you think @mateuszbaran?

The original problem is assuming that points by default belong to a manifold, and I don't think we actually need that assumption anywhere because all manifolds implement (or should implement) checks for points and tangent vectors. The more correct default seems to be that a point does not belong to a manifold, and it could be applied not just to `ProductManifold` but I think any `AbstractManifold`.

**Comment by kellertuer** [comment]
> > So concerning 2) I feel a little strange that a group manifold is an abstract embedded manifold, I would have thought it is a decorator sure, but more like the metric manifold (where for sure the current path spares quite a few transparency rules to be defined) - so while a lazy less code approach here is nice, maybe we want to avoid that all group manifolds are embedded manifolds?
> > To avoid as many definitions as we do in Metric manifold, one could introduce a `Transparency Level` or `TransparencyType` already for the decorator level (similar as we do for embedded manifolds) to avoid lengthy transparency definitions as we currently have in metric manifold.
> 
> Yes, sure, putting forwarding types directly in decorator seems to be a better idea than making `AbstractGroupManifold` embedded.

I will think about a system that works similar to what we do at embeddedmanifold, maybe even the same but introducing it a level earlier, so that this simplifies.

> 
> > Concerning 4) Maybe we could introduce an error for `check_point(::ProductManifold, p)` when `p` is not a `ProductRepr` that it is of the wrong form? Or at least if it is neither a `ProductRepr` nor a `Tuple`? What do you think @mateuszbaran?
> 
> The original problem is assuming that points by default belong to a manifold, and I don't think we actually need that assumption anywhere because all manifolds implement (or should implement) checks for points and tangent vectors. The more correct default seems to be that a point does not belong to a manifold, and it could be applied not just to `ProductManifold` but I think any `AbstractManifold`.

This is a breaking change, but I think that it is quite reasonable, especially when these cases with so different types appear, then the default to say - it is not on the manifold, is better.

**Comment by mateuszbaran** [comment]
> I will think about a system that works similar to what we do at embeddedmanifold, maybe even the same but introducing it a level earlier, so that this simplifies.

Great, that would be a nice solution.

> This is a breaking change, but I think that it is quite reasonable, especially when these cases with so different types appear, then the default to say - it is not on the manifold, is better.

It's breaking but I'd be fine with calling it a bugfix :slightly_smiling_face: .

**Comment by kellertuer** [comment]
> > I will think about a system that works similar to what we do at embeddedmanifold, maybe even the same but introducing it a level earlier, so that this simplifies.
> 
> Great, that would be a nice solution.

Ok, this will be my next project then.

> 
> > This is a breaking change, but I think that it is quite reasonable, especially when these cases with so different types appear, then the default to say - it is not on the manifold, is better.
> 
> It's breaking but I'd be fine with calling it a bugfix 🙂 .

Ok, sure.

**Comment by kellertuer** [comment]
So we updated the type system, but the error still persists; I will have to check where we now have to introduce an in transparency I think.
