### ISSUE TITLE
getindex for decorators

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#364]
When typing the answer to #363 I noticed two things that might be nice

* `allocate(p::ProductRepr)` that allocates a new `ProductRepr` with the same `parts` as `p`
* `p[M,i]` should be transparent for decorators (so this is maybe also something for `ManifoldsBase.jl`, since it is related to the decorator manifold?

**Comment by mateuszbaran** [comment]
Yes, both make sense. I can work on the first point but the second one looks complicated (it's the first time our decorator isn't applied to the first argument of a function).

**Comment by kellertuer** [comment]
One could just really actually bypass our normal mechanism and pass it down like
`getindex(p,M::Metricmanifold,i) = getindex(p,M.manifold,i)` (or even on the abstract decorator level).

**Comment by mateuszbaran** [comment]
Ah, yes, that is an easy solution :smiley: .

**Comment by mateuszbaran** [comment]
Hm, `allocate` does work with `ProductRepr` for me, could you give an example of what's missing?

**Comment by kellertuer** [comment]
Interesting, then maybe I confused something yesterday (though on my other computer), since now here it also works.
