### ISSUE TITLE
Rename `get_point_coordinates` to `get_parameters`

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#370]
I was not so happy with the name `get_point_coordinates` back in #325, and while looking for hat/vee the last few minutes, I remembered one terminology that might fix/help here.

If we have a chart (U,φ) then the inverse of the chart is also called a parametrisation. For example do Carmo, Riemannian Manifolds, Chapter 0, Section 2, even defines Manifolds using an atlas of parametrisation.
So if we have a point `p` on the manifold and its image `x=φ(p)` in R^n it can be seen as parameters to this point (and the inverse, the parametrisation brings back the point `p=φ^-1(x)`, where `x` are the coordinates in the chart `φ` or in other words the parameters `x` in the parametrisation `φ^-1`.

So, I feel `get_parameters` would be a very nice name. I would extend the documentation accordingly if this change is accepted (and maybe so early on this can - with a slight misuse) still be seen as non breaking?

**Comment by mateuszbaran** [comment]
How about calling it `get_parametrisation`?

Other than that I'm fine with it, and I doubt anyone uses `get_point_coordinates` so we could call this change a "bugfix".

**Comment by kellertuer** [comment]
for me `get_parametrization` would be a name of a function returning the whole function `φ^-1`? So it would be more like the opposite of `get_chart`?

**Comment by mateuszbaran** [comment]
OK then, I don't really like either name so it could be `get_parameters` as well.

**Comment by kellertuer** [comment]
If you don't like any of them, we can also look for another one? Indeed it is sometimes hard to find good names ;)

**Comment by mateuszbaran** [comment]
It would be nice if there was a better name :slightly_smiling_face: . Two that I just thought of are `chart_parameters` and `point_parameters`, or maybe something else without `get_`?

**Comment by kellertuer** [comment]
Well from a similar regime we currently have
`get_coordinates`/`get_vector` (tangent vector and basis decomposition)
and here `get_point` for the second (I like the similarity of point/vector `get`ers for the “way back” to the manifold/tangent space.
Thats why I am looking for a `get_X` to fit the coordinate function. Let's see
* do Carmo calls the inverse chart a parametrisation or system of coordinates.
* Jost called them local coordinates
* Absil/Mahony/Sepulche at first glance do not name it
* Boumal calls it local parametrization
* Lee calls the resulting local coordinates.

So even in literature this is quite different.

**Comment by mateuszbaran** [comment]
So maybe `get_local_parameters`? Or `get_local_coordinates`?

**Comment by kellertuer** [comment]
th current `get_coordinates` are also local (in a tangent space) – so there the p specifies the locality kind of. Here, the chart (or chart index to be precise) would also (implicitly as a function argument) kind of denote the locality, I think?

Among your two I would prefer the `get_local_parameters` to strictly distinguish between coordinates (basis component prefactors) and parameters (numbers to reconstruct a point in using a chart/parametrisation). But even more, I would favour leaving out the local.

**Comment by mateuszbaran** [comment]
> th current `get_coordinates` are also local (in a tangent space) – so there the p specifies the locality kind of. Here, the chart (or chart index to be precise) would also (implicitly as a function argument) kind of denote the locality, I think?

The coordinates of tangent vectors are kind of global, since they refer to a basis that spans the entire tangent space. This is in contrast to a chart which doesn't have to cover the entire manifold, and its inverse doesn't have to be defined over the entire R^n.

Anyway, as I said, I'd be fine with `get_parameters`.

**Comment by kellertuer** [comment]
Then I maybe misunderstood you somewhere inbetween ;) I will switch to `get_parameters` then with a bugfix-PR the next days.
