### ISSUE TITLE
Reduce ambiguities with cotangent vectors

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#376]
I just took a look at the ambiguities we currently have and it seems most come from
`get_vector`, `get_coordinates` in relation with the cotangent Riesz representer. Is there an easy fix for this?
This yields all the ambiguities wrt ManifoldsBase (66 is the bound we need for 1.5 in 1.6 I think its 47)

Also we should work on Ambiguities of Manifolds (which is zero in 1.5 and this is tested but 189 in 1.6).

**Comment by mateuszbaran** [comment]
Yes, we should definitely reduce the number of ambiguities. I just keep postponing it because they usually correspond to unlikely corner cases (and even if someone hits it there is little harm in that, no wrong answer would be given so it's relatively harmless) or sometimes even calls that wouldn't make much sense.

**Comment by kellertuer** [comment]
Sure, since that is some interplay between ValidationManifold and Basis, I will take a look whether some of these can easily be reduced.

**Comment by kellertuer** [comment]
So a few things I noticed

## Operations with other Packages / Identity
I a few occurrences we have ambiguities with other packages like for example

````
*(s, comp::ChainRulesCore.Tangent) 
in ChainRulesCore at 
ChainRulesCore/fsJxJ/src/differential_arithmetic.jl:190,
vs
*(::Identity{G, PT} where PT, p) where G<:(AbstractGroupManifold{𝔽, MultiplicationOperation, T} where {𝔽, T<:AbstractEmbeddingType})
in Manifolds at
Manifolds.jl/src/groups/group.jl:983)
````

so I think we can not get rid of these?
The arithmetic operators all appear with identity since then one argument is typed the other not.
These are
* 44 with ChainRulesCore.jl (all `+`,`-`,`*`,`/`)
* 4 with DoubleFloats.jl (all `+`,`-`,`*`,`/`)
* 7 with Intervals.jl (all `+`,`-`,`*`,`/`)
* 10 with Polynomials.jl (´+`,`-`+`*`,`/`,ìsapprox`,`mul!`)
* 4 with SpecialFunctions (all `*`)
* 8 LightGraphs (`*`,`mul!*`)

and further
* 4 set/getindex with StaticArrays.jl
* 2 getindex with SparseArrays.jl
* 1 set index with ReverseDiff.jl

'' Own Identity problems

We even manage to do this with ourselves 
````
*(::Identity{G, PT} where PT, p) where G<:(AbstractGroupManifold{𝔽, MultiplicationOperation, T} where {𝔽, T<:AbstractEmbeddingType})
in Manifolds at
Manifolds.jl/src/groups/group.jl:983,
vs
*(p, ::Identity{G, PT} where PT) where G<:(AbstractGroupManifold{𝔽, MultiplicationOperation, T} where {𝔽, T<:AbstractEmbeddingType})
in Manifolds at 
Manifolds.jl/src/groups/group.jl:984
```` 
which I fear currently means that multiplying with the identity might not work? But I fear we would have to type `p` to solve this?

* 22 where we have this with `+`,`-`,`*`,`/`, `get_vector`, `get_coordinates`
* 15 times with `allocate_result` and `Identity` (on AbstractManifold) where it conflicts with PowerManifolds allocate (where the function is not typed)

## ProductArray
* 7 cases where `ProductArray`s get/setindex conflicts with our generic PowerManifold get/set – we could solve with by having also the manifold in the ProductArrays get/set but it will be deprecated anyways right?

## Atlas
Further we have
* 3 with  `ManifoldsBase.CotangentSpaceType` and in the default orthonormal basis and
* 32 with `ξr::Manifolds.RieszRepresenterCotangentVector` because otherwise `get_coordinates!` and `get_vector! do not type this Mainly this is in relation with ValidatorManifold or DecoratorManifold
```
get_coordinates!(M::AbstractManifold, v, p, ξ::Manifolds.RieszRepresenterCotangentVector, ::DefaultOrthonormalBasis{𝔽, ManifoldsBase.CotangentSpaceType}) where 𝔽
in Manifolds at
Manifolds.jl/src/cotangent_space.jl:60
vs
get_coordinates!(M::ValidationManifold, Y, p, X, B::AbstractBasis; kwargs...)
in ManifoldsBase at
ManifoldsBase.jl/src/ValidationManifold.jl:279
```
or
```
get_coordinates!(M::AbstractManifold, v, p, ξ::Manifolds.RieszRepresenterCotangentVector, ::DefaultOrthonormalBasis{𝔽, ManifoldsBase.CotangentSpaceType}) where 𝔽
in Manifolds at
Manifolds.jl/src/cotangent_space.jl:60
vs
get_coordinates!(M::AbstractDecoratorManifold, Y, p, X, B::DefaultOrthonormalBasis)
in ManifoldsBase at
Julia/ManifoldsBase.jl/src/DecoratorManifold.jl:358
```

## Misc
I have two that are a little mean since I am not sure how to resolve them

```
inverse_retract!(::MetricManifold{ℝ, Stiefel{n, k, ℝ}, CanonicalMetric}, X, p, q, a::ApproximateInverseRetraction) where {n, k}
in Manifolds at Manifolds.jl/src/manifolds/StiefelCanonicalMetric.jl:154
inverse_retract!(M::AbstractDecoratorManifold, X, p, q, m::NLsolveInverseRetraction)
in ManifoldsBase at ManifoldsBase.jl/src/DecoratorManifold.jl:358

allocate_result(M::AbstractManifold, f::typeof(get_point), a)
in Manifolds at Manifolds.jl/src/atlases.jl:109
allocate_result(::AbstractPowerManifold{𝔽, var"#s135", NestedReplacingPowerRepresentation} where {𝔽, var"#s135"<:AbstractManifold{𝔽}}, f, x...)
in ManifoldsBase at ManifoldsBase.jl/src/PowerManifold.jl:212)
```
for me it seems that sometimes with explicit undecorating (first case) or handling all functions at once (second case) might have to be handled more carefully maybe?

**Comment by mateuszbaran** [comment]
Thanks for a very detailed analysis! 

> Operations with other Packages / Identity

I guess we could get rid of some of these ambiguities. It would just require going case by case, figuring out if the call causing an ambiguity makes sense and figuring out what to do there.

> which I fear currently means that multiplying with the identity might not work? But I fear we would have to type `p` to solve this?

This looks like a problem with multiplying two identities from different groups, which I think should indeed be undefined -- that is, we would have an ambiguity by design. Of course, giving `p` a type would be a solution that doesn't cause ambiguities but replaces them with having to add lots of new multiplication methods, and all it would do is replacing a "call is ambiguous" error with "no method matching" error.

Anyway, I generally feel that `Identity` gives us much more problems than it solves.

> ProductArray

`ProductArray` is deprecated and I think should be removed sooner rather than later, so there doesn't seem to be much point in fixing these.

> Further we have
> 
> * 3 with  `ManifoldsBase.CotangentSpaceType` and in the default orthonormal basis and
> * 32 with `ξr::Manifolds.RieszRepresenterCotangentVector` because otherwise `get_coordinates!` and `get_vector! do not type this Mainly this is in relation with ValidatorManifold or DecoratorManifold

These are IIRC mostly valid issues, and I spent some time when working on #325 solving similar ambiguities. They are just quite tedious to resolve and properly cover by test.

**Comment by mateuszbaran** [comment]
> for me it seems that sometimes with explicit undecorating (first case) or handling all functions at once (second case) might have to be handled more carefully maybe?

In the first case you probably meant `ApproximateLogarithmicMap` instead of `ApproximateInverseRetraction`?

The second one looks like a real issue but I think the real problem there is general lack of support for product atlases (much larger problem than this single ambiguity).

**Comment by kellertuer** [comment]
Thanks for the feedback, one of my idea was to maybe even solve a few of these – which I could only do for two cases for now (see #377).

> This looks like a problem with multiplying two identities from different groups, which I think should indeed be undefined 

You‘re right, I thought it might also affect any multiplication – but it does not. One way to actually avoid all ambiguities is to define for all these operators (I use `+` here now) `+(e::T, f::T2)` (providing an error message) and `+(e::T,f::T)` – would that be worth doing?

For the Cotangent space and Riesz I think the problem is that for now we did not type the (co)tangent vector and now introducing this on an abstract level causes exactly all the ambiguities, I do not yet have a good idea what to do there.

> In the first case you probably meant ApproximateLogarithmicMap instead of ApproximateInverseRetraction?

A yes, but that does not resolve the ambiguity I fear? We should maybe think about a generic way how to solve ambiguities like these, i.e. we would like to specialise some basis/retractions later and some already on the abstract level.
But I have no good idea yet how to achieve this ( similar to our transparency which I would at some day like to move to smiting without using functions `__something` but maybe with a THTT in an additional first argument?).

**Comment by mateuszbaran** [comment]
> One way to actually avoid all ambiguities is to define for all these operators (I use `+` here now) `+(e::T, f::T2)` (providing an error message) and `+(e::T,f::T)` – would that be worth doing?

I'm not sure, we should probably ask on Slack on discourse.

> For the Cotangent space and Riesz I think the problem is that for now we did not type the (co)tangent vector and now introducing this on an abstract level causes exactly all the ambiguities, I do not yet have a good idea what to do there.

Yes, typing the tangent vector would reduce the number of ambiguities but we did not want to do that. Anyway, I'm not sure if this would solve any real problem: that is, all calls what would work after such change also work now (I think), and for other calls the user just gets a different error message (though maybe a bit more clear one in some cases).

> A yes, but that does not resolve the ambiguity I fear?

What's the ambiguity after this change?

> ( similar to our transparency which I would at some day like to move to smiting without using functions `__something` but maybe with a THTT in an additional first argument?).

The requirements we already have for traits are extremely hard to satisfy. It would be nice to move towards traits but there seems to be no consensus in the Julia community how traits are supposed to be implemented. Our combination of staying relatively close to plain Julia code, zero-cost requirement, good interplay with dynamic dispatch on non-traited arguments and reuse of functions for slightly different purposes (all the ambiguities arising from `injectivity_radius` and bases of vector spaces) make it extremely hard.

Maybe we should turn it into a challenge-like thing and post it on Julia's discourse?

**Comment by kellertuer** [comment]
>> A yes, but that does not resolve the ambiguity I fear?
> 
> What's the ambiguity after this change?

The same, I just changed that type to a more specific one, which did not change the ambiguity per se.

> Maybe we should turn it into a challenge-like thing and post it on Julia's discourse?

I think that is a very good idea, which we though have to phrase carefully, since it is a little more complex chan “just” a THTT, but also the dynamic idea where to dispatch to _and_ these optional parameters at the end (basis or retraction type) make it interesting. Would you mind phrasing/writing that?

**Comment by kellertuer** [comment]
> > One way to actually avoid all ambiguities is to define for all these operators (I use `+` here now) `+(e::T, f::T2)` (providing an error message) and `+(e::T,f::T)` – would that be worth doing?
> 
> I'm not sure, we should probably ask on Slack on discourse.

sounds good, I will do that the next days.

**Comment by kellertuer** [comment]
Ref: https://discourse.julialang.org/t/acid-ambiguities-with-individual-number-element-identity/62465

**Comment by mateuszbaran** [comment]
> The same, I just changed that type to a more specific one, which did not change the ambiguity per se.
> 
> >

That's really weird. We're talking about this, right?
```
inverse_retract!(::MetricManifold{ℝ, Stiefel{n, k, ℝ}, CanonicalMetric}, X, p, q, a::ApproximateInverseRetraction) where {n, k}
in Manifolds at Manifolds.jl/src/manifolds/StiefelCanonicalMetric.jl:154
inverse_retract!(M::AbstractDecoratorManifold, X, p, q, m::NLsolveInverseRetraction)
in ManifoldsBase at ManifoldsBase.jl/src/DecoratorManifold.jl:358
```
If so, changing the type of the fifth argument of the first method to `ApproximateLogarithmicMap` makes them, as far as I can see, very much different because `NLsolveInverseRetraction` and `ApproximateLogarithmicMap` are disjoint. What am I missing here?

> I think that is a very good idea, which we though have to phrase carefully, since it is a little more complex chan “just” a THTT, but also the dynamic idea where to dispatch to _and_ these optional parameters at the end (basis or retraction type) make it interesting. Would you mind phrasing/writing that?

Yes, I'll try writing something like that.

> Ref: https://discourse.julialang.org/t/acid-ambiguities-with-individual-number-element-identity/62465

Great, thanks!

**Comment by kellertuer** [comment]
> If so, changing the type of the fifth argument of the first method to `ApproximateLogarithmicMap` makes them, as far as I can see, very much different because `NLsolveInverseRetraction` and `ApproximateLogarithmicMap` are disjoint. What am I missing here?

Nothing – my bad – I was still on the wrong branch. Fixed it in the ApproxLog branch.

**Comment by kellertuer** [comment]
For the cotangent Riesz I had the following idea, which I can not yet realise, since I am stuck in my (limited) understanding of meta programming. The idea is as follows: if I define 
```
METAMANIFOLDS = [AbstractManifold, AbstractDecoratorManifold, AbstractPowerManifold, ValidationManifold]
```
as all manifolds that define things on a meta level and we just look at the new `get_coordinates!`(line 60 cotangent_space.jl)
one could do something like

```
for TM in filter(x -> x != AbstractManifold, Manifolds.METAMANIFOLDS)
    quote
        @invoke_maker 1 AbstractManifold get_coordinates!(M::$TM, v, p, ξ::RieszRepresenterCotangentVector, b::DefaultOrthonormalBasis{𝔽,CotangentSpaceType})
    end
end
```
just that this does not work, but if all these would be defined (and invoke the AbstractManifolds case) the ambiguities would vanish.
Would something like this maybe be also a nice idea for a macro where the `AbstractManifold` could be taken as the `i`th (here `I=1`) argument type and one would provide a list of types that invoke said types function?

**Comment by kellertuer** [comment]
...ah the usual, when you write down the problem you see a solution, its `eval` not `esc`.

**Comment by mateuszbaran** [comment]
Yes, it might work if the quote is `eval`ed. You can see similar things already existing, for example
```julia
for MT in GROUP_MANIFOLD_BASIS_DISAMBIGUATION
    eval(
        quote
            @invoke_maker 1 AbstractManifold get_vector(
                M::$MT,
                e::Identity,
                X,
                B::VeeOrthogonalBasis,
            )
        end,
    )
end
```

**Comment by kellertuer** [comment]
Exactly. Excluding `Identity` stuff the `ManifoldsBase` ambiguities are down to 17 (get/setindex and a few allocations for power/atlas I think).

Manifolds is down to 38, with a few get vectors left.

**Comment by mateuszbaran** [comment]
Thanks for working on it, this sounds great :slightly_smiling_face: .

**Comment by kellertuer** [comment]
Well I am just running into an inclusion deadlock
 It would be great if the cotangent vectors were aware of the ProductManifold, but

cotangent has to be loaded before ConnectionManifold and that before MetricManifold, and that before Product. So cotangent can not know ProductManifold. I have to think how to resolve this.

**Comment by mateuszbaran** [comment]
The easiest solution I think would be to define the method specific to ProjectManifold in ProjectManifold.jl.

**Comment by kellertuer** [comment]
I think I resolved it. Also I just checked the `our_base_ambiguities()` and they are down from 24 to 4; all of them are related to `issaprox` with identity, so if we at some point agree not to have an identity type, we would not have any of those left.
