### ISSUE TITLE
Cartan-Schouten connections

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#387]
Some recent confusion regarding Lie groups stemmed from not distinguishing appropriately different connections that can be constructed on them. In particular, there are the so-called Cartan-Schouten connections which emerge from the Lie group structure instead of the metric, and some of them aren't torsion-free (so different from the Levi-Civita metric). Here is a preprint about it: https://hal.inria.fr/hal-02342137/document , referenced previously in https://github.com/JuliaManifolds/Manopt.jl/issues/86#issuecomment-864563514 .

I think it would be beneficial to be a bit more explicit with connections when it comes to Lie groups. For example `group_exp` and `group_log` should explicitly state the connection. Probably there should be a single `exp` function that can be provided with any connection and would calculate the exp/log based on that. Similarly for parallel transport, it is crucial to specify which connection is meant when parallel transporting. I think Lie groups provide sufficient motivation to taking connections seriously.

**Comment by kellertuer** [comment]
Here's a few ideas to consider / take into account. this does not mean these ideas are final, but may be discussed

* Introduce an `AbstractConnection` and an abstract subtype `AbstractRiemannianConnection`
* Introduce a concrete subtype `LeviCevitaConnection` which is the default (and is the Levi Cevita connection to the default metric on a manifold)
* introduce a `ConnectionManifold{M,C}` similar to the `MetricManifold`, where the default is the `LeviCevitaConnection`.
* introduce another connection, the `CartanSchoutenConnection`, which is the default connection on `GroupManifolds`.
* Then `exp` on a Lie group defaults to the one w.r.t the `CartanSchoutenMetric`; to get the current default metric, you have to “unpack” the Lie group and get the inner manifold to call its exp.
* For the unpacking one could introduce a retraction that uses a `LeviCevitaRetraction` on Group Manifolds or equip `ExponentialRetraction` with a connection as an optional parameter (which defaults to Levi Cevita)
* Similarly, `ParallelTransport` could be parametrised by a connection (defaulting to Levi Cevita)

In general the `ConnectionManifold` would be very similar to the `MetricManifold` – and writing this, one could also use `ManifoldConnection` but then I would also switch to `ManifoldMetric` for he other decorator.
With this approach, again the current state would stay as it is, since (very similar to the metric) if you want to stay “connection agnostic” and assume to have a default connection, the Levi Cevita for (Riemannian) manifolds, the Cartan Schouten for Lie groups, that is fine.

This would make `group_exp` and `group_log` obsolete and they would just be `exp/log` of the `GroupManifold`.

**Comment by mateuszbaran** [comment]
> * Introduce an `AbstractConnection` and an abstract subtype `AbstractRiemannianConnection`

Would `AbstractRiemannianConnection` be just an affine connection? Or something else?

> * introduce another connection, the `CartanSchoutenConnection`, which is the default connection on `GroupManifolds`.
> * Then `exp` on a Lie group defaults to the one w.r.t the `CartanSchoutenMetric`; to get the current default metric, you have to “unpack” the Lie group and get the inner manifold to call its exp.

The one problem with that is that there are different Cartan-Schouten connections that would fit a group manifold, and there could be an argument made for both '0' and '-' being the default one. And what is `CartanSchoutenMetric`?

> * For the unpacking one could introduce a retraction that uses a `LeviCevitaRetraction` on Group Manifolds or equip `ExponentialRetraction` with a connection as an optional parameter (which defaults to Levi Cevita)
> * Similarly, `ParallelTransport` could be parametrised by a connection (defaulting to Levi Cevita)

I was thinking about a similar approach. It would be way easier to parameterize retractions, inverse retractions and parallel transports than to introduce a new manifold decorator and work out its interplay with metric manifolds and group manifolds. On the other hand, with a decorator, it would be harder to accidentally mix different incompatible structures. Ultimately neither reduces the usefulness of the other one and they don't need to be introduced in the same PR.

**Comment by kellertuer** [comment]
> > * Introduce an `AbstractConnection` and an abstract subtype `AbstractRiemannianConnection`
> 
> Would `AbstractRiemannianConnection` be just an affine connection? Or something else?

All affine ones, yes. We could also name it `AbstractAffineConnection`.

> The one problem with that is that there are different Cartan-Schouten connections that would fit a group manifold, and there could be an argument made for both '0' and '-' being the default one. And what is `CartanSchoutenMetric`?

The `...Metric` was just me mistyping what I meant (`...Connection`). I was not aware that there are several of them, then it might be useful to either have a parameter for them or an `AbstractCartanSchoutenConntection` and subtypes.

> I was thinking about a similar approach. It would be way easier to parameterize retractions, inverse retractions and parallel transports than to introduce a new manifold decorator and work out its interplay with metric manifolds and group manifolds. On the other hand, with a decorator, it would be harder to accidentally mix different incompatible structures. Ultimately neither reduces the usefulness of the other one and they don't need to be introduced in the same PR.

I think I would prefer the decorator in the end, since that is the scheme we do here? The connection would be a feature of the manifold, not of the vector transport/retraction, right? So maybe I am not so much in favour of my own idea to parametrise the retraction and vector types after all. Though we then might have to find an easy way to “access” the inner manifold of a group manifold to use its features (transports/retractions w.r.t. the different connection).

**Comment by mateuszbaran** [comment]
> The `...Metric` was just me mistyping what I meant (`...Connection`). I was not aware that there are several of them, then it might be useful to either have a parameter for them or an `AbstractCartanSchoutenConntection` and subtypes.

I think introducing `AbstractCartanSchoutenConntection` makes sense. "-", "0" and "+" connections are the most natural choices for Cartan-Schouten connections but they are definitely not the only ones.

> I think I would prefer the decorator in the end, since that is the scheme we do here? The connection would be a feature of the manifold, not of the vector transport/retraction, right? So maybe I am not so much in favour of my own idea to parametrise the retraction and vector types after all.

OK, that makes sense. I think actually `AbstractConnectionManifold` might be a type between `MetricManifold` and `AbstractDecoratorManifold` in our hierarchy, and most `MetricManifold` decorator rules could just be extended to `AbstractDecoratorManifold` (most likely we would only need to pay more attention to `inner` and `norm`). It may not be *that* bad after all.

> Though we then might have to find an easy way to “access” the inner manifold of a group manifold to use its features (transports/retractions w.r.t. the different connection).

What do you mean by that? Wouldn't it be the most consistent to just construct a new `AbstractGroupManifold` object to change the connection? We could introduce a new function that just changes the connection of an `AbstractGroupManifold` while keeping its group structure.

**Comment by kellertuer** [comment]
> I think introducing `AbstractCartanSchoutenConntection` makes sense. "-", "0" and "+" connections are the most natural choices for Cartan-Schouten connections but they are definitely not the only ones.

Sounds good!


> OK, that makes sense. I think actually `AbstractConnectionManifold` might be a type between `MetricManifold` and `AbstractDecoratorManifold` in our hierarchy, and most `MetricManifold` decorator rules could just be extended to `AbstractDecoratorManifold` (most likely we would only need to pay more attention to `inner` and `norm`). It may not be _that_ bad after all.

Oh, this sounds nice, sure that makes sense.

> 
> > Though we then might have to find an easy way to “access” the inner manifold of a group manifold to use its features (transports/retractions w.r.t. the different connection).
> 
> What do you mean by that? Wouldn't it be the most consistent to just construct a new `AbstractGroupManifold` object to change the connection? We could introduce a new function that just changes the connection of an `AbstractGroupManifold` while keeping its group structure.

I am thinking about the following: if `group_exp` and `exp` are currently different (the first is CSConnection, the second LCConnection), then with Lie groups and proper connections `group_exp` gets `exp`, but what if we still would like to get “down” into the Lie groups inner manifold and its connection, i.e. call what is now called with `exp`? This would be using the inner manifold.

In order to actually change, I would again wrap the manifold in a `ManifoldConnection` decorator, sure, that is also a way to go; the easier one here is do undecorate instead.

**Comment by mateuszbaran** [comment]
> I am thinking about the following: if `group_exp` and `exp` are currently different (the first is CSConnection, the second LCConnection), then with Lie groups and proper connections `group_exp` gets `exp`, but what if we still would like to get “down” into the Lie groups inner manifold and its connection, i.e. call what is now called with `exp`? This would be using the inner manifold.
> 
> In order to actually change, I would again wrap the manifold in a `ManifoldConnection` decorator, sure, that is also a way to go; the easier one here is do undecorate instead.

Yes, both undecorating or decorating in a new `ConnectionManifold` would be valid approaches for that.

**Comment by mateuszbaran** [comment]
I just looked into introducing these connection decorators and one major obstacle is `AbstractGroupManifold`, which needs to be changed from `AbstractEmbeddedManifold` to `AbstractConnectionManifold`. IIRC `AbstractGroupManifold` was supposed to be modified anyway (with some preliminary work in https://github.com/JuliaManifolds/ManifoldsBase.jl/pull/75 ) so I'm going to wait with doing connections <-> group manifolds integration.

**Comment by kellertuer** [comment]
Yes, it should be changed anyways, since it is not embedded as we usually treat embeddingness; I will try to get back to that PR soon.

**Comment by mateuszbaran** [comment]
I've pushed the main part of extraction of connection manifolds in https://github.com/JuliaManifolds/Manifolds.jl/pull/381 -- that is, I've moved functions related to connections to a separate file and introduced appropriate basic types.

**Comment by mateuszbaran** [comment]
This might be a good place to continue the discussion from https://github.com/JuliaManifolds/ManifoldsBase.jl/pull/75#issuecomment-866661954 about the relationship between `ConnectionManifold` and `MetricManifold`.

**Comment by kellertuer** [comment]
Exactly.

So I think there is one case where all functions the metric overwrites should be transparent, that is for the `LeviCevitaConnection` if the underlying (implicit/default) metric or the `MetricManifoldDecorator` it decorates.

I all other cases, we have to carefully check what is reasonable.

**Comment by mateuszbaran** [comment]
> So I think there is one case where all functions the metric overwrites should be transparent, that is for the `LeviCevitaConnection` if the underlying (implicit/default) metric or the `MetricManifoldDecorator` it decorates.

I'm not sure I completely understand. In #381 I've introduced `AbstractConnectionManifold` and made `MetricManifold` derive from that abstract type, providing the `LeviCivitaConnection`.

Additionally, should `AbstractGroupManifold` (or `GroupManifold`) be an `AbstractConnectionManifold` implementing one of the Cartan-Schouten connections? Should a `GroupManifold` provide `norm` if one chooses to use one of the Cartan-Schouten connections that is not equivalent to the Levi-Civita connection of the decorated manifold?

**Comment by mateuszbaran** [comment]
The safe choice would be to not forward any metric functions through `AbstractConnectionManifold`, including `inner` and `norm`, by default.

**Comment by kellertuer** [comment]
Oh, then you lost me there. In what sense is a `MetricManifold` an `AbstractConnectionManifold`?

I had them as distinct in mind. One decorator is the metric manifold, the other is the connection manifold. I am not sure which is the better way

For a group manifold I am also not sure. Again, if one implicitly assumes that a group manifold comes with a (certain, default) Cartan-Schouten connection, then sure, it should be an `AbstractConnectionManifold`. And then the question is whether this default is equivalent, sure; that can only be clarified by a default (like we do for the metric / embedded transparency).

**Comment by mateuszbaran** [comment]
> Oh, then you lost me there. In what sense is a `MetricManifold` an `AbstractConnectionManifold`?
> 
> I had them as distinct in mind. One decorator is the metric manifold, the other is the connection manifold. I am not sure which is the better way

`AbstractConnectionManifold` would be a supertype for all decorators that override the connection, and `MetricManifold` does override the connection (with the Levi-Civita connection of its metric). This way I could just move about half of the metric manifold methods to `AbstractConnectionManifold`. Somehow `MetricManifold`'s `christoffel_symbols_second`, `christoffel_symbols_second_jacobian`, `gaussian_curvature`, `ricci_curvature`, `ricci_tensor`, `riemann_tensor` and `solve_exp_ode` use exactly the right conventions to work right with connections.

> For a group manifold I am also not sure. Again, if one implicitly assumes that a group manifold comes with a (certain, default) Cartan-Schouten connection, then sure, it should be an `AbstractConnectionManifold`. And then the question is whether this default is equivalent, sure; that can only be clarified by a default (like we do for the metric / embedded transparency).

I'm not sure about group manifold either, very likely Cartan-Schouten metrics should be introduced by a separate `ConnectionManifold` decorator on top of `AbstractGroupManifold`.

**Comment by kellertuer** [comment]
> `AbstractConnectionManifold`  [...]

sounds good, I did not think of that. Nice!
 
> I'm not sure about group manifold either, very likely Cartan-Schouten metrics should be introduced by a separate `ConnectionManifold` decorator on top of `AbstractGroupManifold`.

I think I would prefer a way like we do for the embedded manifold. You have a (default) Cartan-Schouten metric in mind when you implement a group manifold and ou do not want to think about metrics, that's fine.
If you implement a second, then proceed similar to what we currently do with MetricManifolds and a default metric.

**Comment by mateuszbaran** [comment]
> > I'm not sure about group manifold either, very likely Cartan-Schouten metrics should be introduced by a separate `ConnectionManifold` decorator on top of `AbstractGroupManifold`.
> 
> I think I would prefer a way like we do for the embedded manifold. You have a (default) Cartan-Schouten metric in mind when you implement a group manifold and ou do not want to think about metrics, that's fine.
> If you implement a second, then proceed similar to what we currently do with MetricManifolds and a default metric.

The problem is that, depending on whether the default Cartan-Schouten connection is the same as as the Levi-Civita connection of the decorated manifold, the reasonable defaults of the group manifold decorator would be very different. If they are the same, all metric-related functions could just forward to the decorated manifold. Otherwise there should be no forwarding.

@sethaxen Do you have an opinion on whether `AbstractGroupManifold` should be an `AbstractConnectionManifold` or not? And which connection should be the default for `GroupManifold`?

**Comment by kellertuer** [comment]
I don't see a problem there, the group manifold would have different types of transparency then, like the embedded manifold does, too.

**Comment by mateuszbaran** [comment]
Yes, that's an option, I'm just a bit afraid of the complexity of this solution -- but it could definitely work.

**Comment by mateuszbaran** [comment]
Implemented in #381
