### ISSUE TITLE
Switch from `ProductRepr` and `ProductArray` to `ArrayPartition`

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#402]
`ArrayPartition` is a structure from RecursiveArrayTools.jl that serves a very similar purpose to `ProductRepr`. It integrates better with the SciML ecosystem and after a few fixes its performance should be quite good: https://github.com/SciML/RecursiveArrayTools.jl/pull/163 .

**Comment by kellertuer** [comment]
Since we have ArrayPartition already running, this should just be removing some old code?

**Comment by mateuszbaran** [comment]
Yes, that's just removing some code. I can do that.
