### ISSUE TITLE
An overview (Franklin?) page for JuliaManifolds

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#406]
What do you think about getting an overview homepage at juliamanifolds.github.com ? We could (for a start) refer to the separate documentations (currently 2 but soon there will be more) and refer to cool projects / papers using our code?

**Comment by mateuszbaran** [comment]
Cool idea but currently there may not be enough content for a homepage I think. Maybe we could also put there some examples and how-tos?

**Comment by kellertuer** [comment]
If the examples cover more than one of the packages, for sure, yes.

Indeed, currently it might mainly be an overview of packages we have in the org and not much more content – but it might be a nice starting point for “general manifold stuff” in Julia – and we can also have a page for projects depending on us or related / interesting projects in general (wrt manifolds).

**Comment by sethaxen** [comment]
Yeah, I think even just a simple splash page with a logo for each package we consider usable would be useful.

**Comment by kellertuer** [comment]
Then I will set up a first page the next days.

Considering Logos, we currently just have one logo (Manopt has its own, ok), so we could also elaborate on that, yes; maybe variants of the logo?.

**Comment by sethaxen** [comment]
Perhaps, though which packages would we consider usable right now? Manifolds.jl, ManifoldsBase.jl, and ManOpt.jl for sure. Is FunManifolds.jl usable? I think it would be premature to create logos for packages that are still highly experimental and don't have many features yet, and it would probably be premature to list them on the page.

**Comment by kellertuer** [comment]
For now those 3, sure (no O, its Manopt.jl btw, as by the Matlab packages example); We could for now list that exactly the way you mention; 
1. Packages
2. Packages in Preparation.

But even for base we could maybe think of just the frame of the logo or something to illustrate it is the interface...

**Comment by mateuszbaran** [comment]
Some parts of FunManifolds.jl are usable but it's far from being polished, so these three are the only ones that I'd advertise as ready for general usage. And maybe we don't need a separate logo for each package? I'm fine with having them but only having the two we already have would also be fine.

**Comment by kellertuer** [comment]
We now have such a page – even with their own docs, but also combining all other docs: https://juliamanifolds.github.io/
