### ISSUE TITLE
Possible performance issue with `get_vector`

### ISSUE THREAD

**Issue by Affie** [JuliaManifolds/Manifolds.jl#412]
I'm seeing a possible performance issue at `get_vector` in some of the functions I'm updating to Manifolds.
If I compare SpecialOrthogonal, TranslationGroup, and SpecialEuclidian, it looks like SpecialEuclidian has extra allocations.
The other manifold I saw had a possible performance issue was a `ProductManifold(SpecialEuclidean(2), TranslationGroup(2))` where I updated to manifolds and the runtime of the tests increased from 20min to 60 min. ProfileView shows get_vector might be the bottleneck, but I get lost in the macros to track it down.

Here is the comparison of SpecialOrthogonal, TranslationGroup, and SpecialEuclidian:
```julia
julia> using Manifolds
julia> M = SpecialOrthogonal(2);
julia> ϵ = identity_element(M);
julia> Xc = [pi/4];
julia> X = get_vector(M, ϵ, Xc, DefaultOrthogonalBasis());
julia> @time get_vector(M, ϵ, Xc, DefaultOrthogonalBasis());
  0.000006 seconds (1 allocation: 112 bytes)
julia> @time get_vector!(M, X, ϵ, Xc, DefaultOrthogonalBasis());
  0.000005 seconds

julia> M = TranslationGroup(2);
julia> ϵ = identity_element(M);
julia> Xc = [1.,2];
julia> X = get_vector(M, ϵ, Xc, DefaultOrthogonalBasis());
julia> @time get_vector(M, ϵ, Xc, DefaultOrthogonalBasis());
  0.000003 seconds (1 allocation: 96 bytes)
julia> @time get_vector!(M, X, ϵ, Xc, DefaultOrthogonalBasis());
  0.000002 seconds

julia> M = SpecialEuclidean(2);
julia> ϵ = identity_element(M);
julia> Xc = [1, 2, pi/4];
julia> X = get_vector(M, ϵ, Xc, DefaultOrthogonalBasis());
julia> @time get_vector(M, ϵ, Xc, DefaultOrthogonalBasis());
  0.000116 seconds (141 allocations: 10.703 KiB)
julia> @time get_vector!(M, X, ϵ, Xc, DefaultOrthogonalBasis());
  0.000018 seconds (9 allocations: 576 bytes)
```

**Comment by kellertuer** [comment]
Interesting to know! I think we have not yet Profiled them for performance.
The general idea we use is
`get_vector` allocates memory and calls `get_vector!`, which itself should not allocate, that's right, we have to look there.
Also on `ProductManifolds` this should just happen component wise basically,
and any group (`ProductGroup`, too, for example) should just act transparently, i.e. as if it was not there...

I first thought it might be the identity (if you use `Identity(M)` it might “materialise” into a full point with memory, but it can also be the `get_vector!` on the semi direct product group (see [here](https://github.com/JuliaManifolds/Manifolds.jl/blob/ee0cc7d7df21c234c4b0a8fd72d5906f468c8076/src/groups/semidirect_product_group.jl#L176-L188)) (maybe the `dim`s ?
 
Sorry that your code gets so much slower – we should definitely investigate together where that comes from.

**Comment by mateuszbaran** [comment]
I'm looking into this. It seems like there are some type instabilities in `get_vector!` on product manifolds but they should be fixable.

**Comment by mateuszbaran** [comment]
OK, I've managed to get it down to about 30ns:
```julia
julia> @benchmark get_vector!($M, $X, $ϵ, $Xc, $B)
BenchmarkTools.Trial: 10000 samples with 995 evaluations.
 Range (min … max):  29.321 ns … 171.310 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     29.829 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   29.924 ns ±   1.756 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

         █▁ ▆▃                                                  
  ▄▆▆▄▄▄▆█████▄▃▂▂▂▂▃▂▂▁▂▁▁▂▁▁▂▂▁▁▁▁▁▁▂▂▁▁▁▁▁▁▁▁▁▂▂▂▂▂▂▂▂▂▂▂▂▂ ▃
  29.3 ns         Histogram: frequency by time           33 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```
I'll make a patch in a moment.

**Comment by mateuszbaran** [comment]
And here is what the non-mutating function will be like:
```julia
julia> @benchmark get_vector($M, $ϵ, $Xc, $B)
BenchmarkTools.Trial: 10000 samples with 935 evaluations.
 Range (min … max):  111.125 ns …   4.552 μs  ┊ GC (min … max):  0.00% … 96.69%
 Time  (median):     115.766 ns               ┊ GC (median):     0.00%
 Time  (mean ± σ):   133.625 ns ± 234.802 ns  ┊ GC (mean ± σ):  11.36% ±  6.25%

   ▆██▇▆▄▃▂▂▂▁▂▁▁                                               ▂
  ▇███████████████▇▇▇▇▆▇▇▆▆▆▆▆▇▇▇█▇▇▇▆▇▆▆▆▅▄▅▃▅▁▅▃▄▄▁▄▁▅▅▅▅▅▇▆▇ █
  111 ns        Histogram: log(frequency) by time        191 ns <

 Memory estimate: 208 bytes, allocs estimate: 2.
```

**Comment by kellertuer** [comment]
I would also be quite interested in how this influenced the runtime of the tests.

**Comment by Affie** [comment]
Hi, thanks for the very quick fix. I updated to the mutating version and ran a quick test that took more than 30 min yesterday. It is down to just over a minute. :rocket: 
I still need to look at the non-mutating version as it looks like the choice of basis influences the speed. We are still figuring out how to deal with different basis choices, but for now, it is just hardcoded to one. 

Maybe there are still some issues as shown by the next code. But I'm very happy with the current performance of the mutating one.
```julia
julia> @time get_vector(M, ϵ, Xc, Manifolds.VeeOrthogonalBasis());
  0.000017 seconds (10 allocations: 448 bytes)

julia> @time get_vector(M, ϵ, Xc, DefaultOrthogonalBasis());
  0.000106 seconds (133 allocations: 10.172 KiB)
```
Thanks again, I'll still do the full test when I have some time and give you an update.

**Comment by kellertuer** [comment]
Yes, depending on the Basis you choose, we sometimes have tricky ways to speed up computation and avoid memory allocations, but it might be that you end up with a `CachedBasis` – that is we store all `manifold_dimension(M)` vectors _explicitly (and also allocate memory for them) and then do the classical coeffcicient * basis vector summation to reconstruct the vector

https://github.com/JuliaManifolds/ManifoldsBase.jl/blob/2596e0ee84e1c4d6665fbb553707654f02cd8851/src/bases.jl#L631-L652

With so many manifolds and bases that we have, I am not sure whether that might be the case for you, but if you run into this case, I expect the allocations for sure :)

In your case `SpecialOrthogonal` should use the methods from `Rotation`(for tangent spaces we kinda ignore the group part is the short explanation here) – that should be fine (see [here](https://github.com/JuliaManifolds/Manifolds.jl/blob/f4d682060b551c5e02c5011f61f1fc4a71b84a4c/src/manifolds/Rotations.jl#L320-L350), no complete construction of the basis).

For `SpecialEuclidean` i.e. a `ProductManifold` (again we strip away the groups for tangent space funs), hm, this should also be fine, since that was what Mateusz just optimised ([here](https://github.com/JuliaManifolds/Manifolds.jl/blob/f4d682060b551c5e02c5011f61f1fc4a71b84a4c/src/manifolds/ProductManifold.jl#L532-L547)).

So just looking at the code (sorry did not have time to actually program/benchmark, just 10 minutes to spare) I do not see where the 133 allocations come from.

**Comment by Affie** [comment]
I can confirm that there is still something strange with the non-mutating version. I updated another function I have to just allocate the result before `vee` and I get an improvement from 3 min to less than 10 seconds.

```julia
pose_res = Vector{Float64}(undef, 3)
vee!(M, pose_res, q, log(M, q, q_hat))
```
I don't know if it will help but here is a part of the profile:
![image](https://user-images.githubusercontent.com/6612981/129166155-0be63515-d89c-47a2-b116-6da0a20d8a0f.png)

orange: ~/.julia/packages/ManifoldsBase/Md56K/src/DecoratorManifold.jl:427, get_coordinates__parent [inlined]
blue: ~/.julia/packages/ManifoldsBase/Md56K/src/DecoratorManifold.jl:390, get_coordinates [inlined]
purple: ~/.julia/packages/ManifoldsBase/Md56K/src/bases.jl:907, vee [inlined]

I can update to using the mutating versions for now.

**Comment by mateuszbaran** [comment]
I've investigated it a bit and will put another patch today. Things like 100+ allocations can relatively easily go away, these are type instabilities that are relatively easy to fix, although certain parts of Manifolds.jl are relatively demanding for the compiler, requiring quite a lot of constant propagation and inlining for optimal performance.

Only relatively few methods of `get_vector`, `get_coordinates` and their mutating variants were well optimized so there is some work left to do.

Also note that using plain `Array`s, especially in non-mutating variants, will always reduce performance. I think you should consider using either non-mutating variants + `SArray`s or mutating variants + `MArray`, `SizedArray` or `Array`, and then we can focus on improving performance in one of these approaches.

**Comment by Affie** [comment]
Thanks @mateuszbaran. The plan is definitely to upgrade to StaticArrays, but we are taking baby steps and first just want to get Manifolds.jl integrated.
