### ISSUE TITLE
Support projection matrix points for Grassmann

### ISSUE THREAD

**Issue by sethaxen** [JuliaManifolds/Manifolds.jl#417]
What would it take to allow representing points on the Grassmann manifold as the unique projection matrix `P = X X'`, where `X` is a point on the Stiefel manifold, instead of `X` as we currently do?

The reason for considering this is that for ManifoldMeasures, we especially want to support measures in PPLs, where identifiability is a major concern. So even though `X` is more efficient for storage, indeed much more efficient when `n>>k`, it may be that the non-identifiability of the `X` representation for a Grassmann variable would cause adaptive sampling strategies like HMC to become even slower.

I imagine to do this via dispatch, we'd need to implement a custom `ProjectionMatrixPoint` or something like that, right?

Or are there more storage efficient unique representations of points on the Grassmann manifold?

**Comment by kellertuer** [comment]
In the draft (see atop) I started implementing the projection representation approach, the question is now – which functions would you like to have – I think that even the metric might first require more work on a structure/interface for quotient manifolds (cf #205), especially horizontal and vertical lift; concerning representations one could think of a quotient manifold even as an `AbstractEmbeddedManifold` subtype.

So for short: Which functions would you like to see included in #443 (for now it is just checks).

**Comment by mateuszbaran** [comment]
Probably exponential map and vector transport would be fine as a start? There are some formulas here: https://arxiv.org/abs/2011.13699 .

**Comment by kellertuer** [comment]
The exponential map (and `inner`) require the horizontal lift. That's why I think these would fit better only after having proper support for quotient manifolds.

**Comment by mateuszbaran** [comment]
We could skip that for this representation but indeed it would be better to do this more generically by introducing horizontal lifts.

**Comment by kellertuer** [comment]
I would maybe finish this issue/PR without those and add them as soon as we have that support? Indeed the simple idea is to have a `AbstractQuotionsmanifold <: AbstractEmbeddedManifold` (again for a default manifold being a quotient already) and a `QuotientManifold{M,N}` to model M as a quotient of N with all the nice functions one can have then (vertical, horizontal lifts, projection...)

**Comment by mateuszbaran** [comment]
I think it's fine to merge #443 without functions requiring lifts but I'm not sure if that would resolve this issue.

**Comment by kellertuer** [comment]
I am also not sure - hence the question. Sure we can continue this after #205 is done and keep this open until then. What do you think @sethaxen ?

**Comment by kellertuer** [comment]
resolved by #443
