### ISSUE TITLE
The Real Symplectic Stiefel Manifold

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#418]
Maybe it would be nice to also include some symplectic manifolds, see for example https://arxiv.org/abs/2108.12447 for some recent developments.

They also include some gradient conversion (Euclidean to X) we started (but never finished) in #44 to discuss.

This issue is just to keep track of the Symplectic ideas – might take that as a next project (once I finished my ideas in ManifoldsBase about maybe rewriting the Group Action stuff).

**Comment by mateuszbaran** [comment]
Good idea, though we should probably start with something more simple like the [symplectic group](https://en.wikipedia.org/wiki/Symplectic_group).

I'll go back and look again at that group action stuff probably tomorrow.

**Comment by kellertuer** [comment]
Sure. My idea was to start with the easy ones and slowly work up to the manifold in the paper.
