### ISSUE TITLE
Nightly tests only on a certain label?

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#436]
Currently the nightly testa re nearly always failing; I was thinking that it is maybe a good idea to move them to a form similar to the docs, i.e. we only run them if one activates that with a certain label … what do you think?

**Comment by kellertuer** [comment]
Hm, the last time it worked on master ist beginning of August; I don‘t care whether they run often, but if they basically always fail – there is no much use in having them?

**Comment by kellertuer** [comment]
I did not say it is completely useless, but we could maybe run it only on certain PRs (like docs) or only on PRs but not on master?

**Comment by mateuszbaran** [comment]
Sure, it does not make sense to run it on master. Anyway, I wouldn't mind having to add a label to have tests run on master.

**Comment by kellertuer** [comment]
For master I am not sure how you would want to add the label, but we could for example exclude nightlies from running on master.

**Comment by mateuszbaran** [comment]
Sorry, I meant PR branches, not master.

**Comment by kellertuer** [comment]
Ah ok, so we would not run Nightlies on master and for PRs we have to decide whether to do that by label or still in general as now? I have no strong preference there.

**Comment by kellertuer** [comment]
Perfect, so we just exclude nightlies from master. I can do that tomorrow.
