### ISSUE TITLE
StackOverflowError: rand(uniform_distribution(sphere), 509)

### ISSUE THREAD

**Issue by aterenin** [JuliaManifolds/Manifolds.jl#449]
As far as I've been able to understand, the right way to draw random samples from a uniform distribution on the sphere is as follows, but that errors.

```julia
sphere = Sphere(2)
haar_measure = uniform_distribution(sphere, zeros(representation_size(sphere)))
x = rand(haar_measure, 509)
```

```julia
ERROR: StackOverflowError:
Stacktrace:
 [1] rand!(rng::Random._GLOBAL_RNG, A::Vector{Any}, X::ProjectedPointDistribution{Vector{Float64}, Sphere{2, ℝ}, Distributions.IsoNormal, typeof(project!)}) (repeats 79984 times)
   @ Random /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/Random/src/Random.jl:267
```

**Comment by sethaxen** [comment]
Ah, I've seen this before, and I believe it's because Distributions added some overloads some ways back that breaks this for non-standard Distribution types. We can fix kt here.

**Comment by kellertuer** [comment]
Oh, and while we are at it, maybe we could rename the function? It seems not to be uniform?
We take the uniform distribution on the unit cube, if I read that correctly and project that onto the sphere.

I am not an expert on distributions, but some points (for example `1/sqrt(n)*ones(n)`) have longer lines that get projected onto them then others (north Pole), so I think the resulting distribution we currently do is not uniform, but a projection of a uniform distribution only. 
We could – but probably over in measures, take the approach from Manuel Gräf https://www-user.tu-chemnitz.de/~potts/workgroup/graef/quadrature/index.php.en in quadrature and compute the same as he does for uniform points of a certain size? And maybe this is also already kept in mind or taken care of in ManifoldMeasures (did not yet have the time to look more into that, but I'd love to do that).

For the actual fix required here – I am not experienced enough with distributions in Julia.

**Comment by mateuszbaran** [comment]
> Oh, and while we are at it, maybe we could rename the function? It seems not to be uniform?
> We take the uniform distribution on the unit cube, if I read that correctly and project that onto the sphere.

Are you sure? I think we take the standard normal distribution on R^n and project that, it should be correct.

**Comment by sethaxen** [comment]
> Oh, and while we are at it, maybe we could rename the function? It seems not to be uniform?
> We take the uniform distribution on the unit cube, if I read that correctly and project that onto the sphere.

Which function are you looking at? I see this one:

https://github.com/JuliaManifolds/Manifolds.jl/blob/845aef6281f38b02c48c37ccf04e815527d8b7fa/src/manifolds/Sphere.jl#L458-L461

So it draws from a standard multivariate normal and projects it to the sphere, which produces the uniform (Hausdorff) measure on the sphere.

> For the actual fix required here – I am not experienced enough with distributions in Julia.

I'll take a stab at this later today if someone doesn't beat me to it.

**Comment by sethaxen** [comment]
For reference, here's where I fixed this in a Manifolds dependency: https://github.com/salilab/EnsembleInference.jl/pull/22
