### ISSUE TITLE
Add a backend RiemannieanProjectedBackend that stores the Euclidean gradient

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#454]
If we have a gradient in the embedding it would be cool to have a backend in `RiemannianProjectedBackend` that just evaluates the Euclidean Gradient.

**Comment by mateuszbaran** [comment]
Isn't this already possible by just accessing `diff_backend` field of `RiemannianProjectionBackend` and calling `_gradient` with it?

**Comment by mateuszbaran** [comment]
Yes, if projection and metric change are identity then just using the wrapped `diff_backend` is fine. The only potential use case for something like `EmbeddedIdentityBackend` would be overriding projection and metric change of the manifold but I don't see why would you want to do that.

**Comment by mateuszbaran** [comment]
Ah, that's not currently possible. I'd say that we should have a separate function for that actually. It would be then called in `gradient!(M::AbstractManifold, f, X, p, backend::RiemannianProjectionBackend)`.

**Comment by kellertuer** [comment]
I would have thought to dispatch on another `EmbeddedBackend` within the Reimannian_projection_Backend – because we have the call to the embedding gradient in `gradient!` (just that for now it can only use ForwardDiff etc but not just a function call).

**Comment by kellertuer** [comment]
That is my plan. I know what to do there, I just wanted to make sure I did not miss anything. I already assigned this to myself, because (without documentation) this is about 5 lines of code.
