### ISSUE TITLE
manifold_point_error can't return multiple independent issues

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#47]
As discussed in #46 , the current approach to error checking allows reporting only a single error at a time. For some manifolds (for example product and power manifolds) multiple independent issues may arise at the same time. We should have a way to report all of them in `manifold_point_error`.

Ref #24 .

**Comment by kellertuer** [comment]
I think I found a good solution, for power and product, within `check_manifold_point` or `check_tangent_vector` do

1. call all checks, collect results in a vector,
2. if all entries are `nothing` (maybe Filter out `nothing`s and check whether empty)
3. if the result of 2 is not empty, wrap that in a `CompositeException` https://docs.julialang.org/en/v1/base/base/#Base.CompositeException
return that.

**Comment by mateuszbaran** [comment]
That is a good solution.
