### ISSUE TITLE
Dark Mode banner in Readme

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#477]
Just a small fix (when we have the dark mode banner in the repo)

https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/

to fix the readme here and in ManifoldsBase to display a bette fitting banner in dark mode (which annoyed me for the last year at least not to have this)

**Comment by kellertuer** [comment]
Here is a first try

https://github.com/JuliaManifolds/Manifolds.jl/blob/kellertuer/dark-logo-readme/README.md

which does neither work in Safari nor in Chrome on Mac OS, so I am not sure what the beta blog is talking about; I basically copied their approaches (and for now linked to the images on exactly that branch).

**Comment by mateuszbaran** [comment]
I tried that Readme and it doesn't change for me either (Linux Mint + Chrome). Maybe because it's still a beta thing?

**Comment by kellertuer** [comment]
It does work on the branch now (you just have to go to the second to last commit, the newest one is already adapted to master),
the problem is, that since it is beta, it dos not yet rewrite blob/ to raw/, but now that I link to raw it does work :)
