### ISSUE TITLE
Kendall Shape Space

### ISSUE THREAD

**Issue by jakubMitura14** [JuliaManifolds/Manifolds.jl#504]
Hello I have a lot of small shapes that I need to compare and I need invariance to scale and rotation, I consider comparing them in Kendall shape space like for example in [1] and [2]
Can it be done in Julia? are there any metrics describing shape similarity implemented?

[1] https://github.com/geomstats/geomstats/blob/dafcbed9e4148733cdc63ae8ff1ce93fc660e09c/geomstats/geometry/pre_shape.py
[2] https://geomstats.github.io/notebooks/14_real_world_applications__hand_poses_analysis_in_kendall_shape_space.html

Thanks!

**Comment by kellertuer** [comment]
Sure, in general this can be implemented.

But for now these are not yet implemented, since we are only here main developers. If you would like to try we can surely help, but at the moment I personally do not have the time to implement that for you.

**Comment by mateuszbaran** [comment]
Cool! I've worked with Kendall's shape spaces long time ago (before I've started working on Manifolds.jl) so I can definitely help here. 

In my experience it's easiest to implement a new manifold starting from an existing one, for example you can take `Sphere.jl` file and do something similar, just replacing `Sphere` with your new manifold name. Alternatively `GrassmannProjector.jl` is a quotient manifold so it shows that you can have things like a horizontal_lift.

In comparison to geomstats, I think Manifolds.jl look quite good -- our performance is often better, we have most of their operations supported + optimization using Manopt.jl. Geomstats has tangent PCA in its examples but it's also easily doable, you can do geodesic regression: https://manoptjl.org/stable/tutorials/GeodesicRegression/ and, for example, I'm currently finishing exact principal geodesic in Manifolds.jl.

**Comment by mateuszbaran** [comment]
Good news, I've started working on this: #550 :slightly_smiling_face:

**Comment by jakubMitura14** [comment]
Oh fantastic! Because I was unable to make any progress

**Comment by mateuszbaran** [comment]
The PR is now merged and there is a tutorial how to use it: https://github.com/JuliaManifolds/Manifolds.jl/blob/master/tutorials/hand-gestures.jl . Let me know if you need more help.

**Comment by jakubMitura14** [comment]
It is absolutely fantastic If I will meet you in any conference you have a bottle of alcohol from me !

**Comment by kellertuer** [comment]
Until then cite us when you use our software and let us know if we can help somewhere with that manifold further :)

**Comment by jakubMitura14** [comment]
of course :), for now I suspended the project for various reasons but I can't wait to get back to it :)
