### ISSUE TITLE
Faster SPD using Cholesky

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#505]
Cholesky decomposition is usually much faster than symmetric eigenvalue decomposition. LDLt decomposition that can be obtained from Cholesky like here: https://services.math.duke.edu/~jdr/2021f-218/materials/week11.pdf should be enough to replace most, if not all, calls to `eigen`.

The difference can be more than an order of magnitude.

**Comment by dehann** [comment]
Hi, sure this is familiar but just in case, Distributions.jl went through a big upgrade to support various matrix structure optimizations, e.g. MvNormal actually dispatches to Diagonal, triangular, etc. covariance matrix types -- presumably for speed and memory.  Might be a good reference for to see how they used LinearAlgebra.jl which may already have many of the dispatches etc. required.

**Comment by mateuszbaran** [comment]
Hi! Good to know but we're not at that level of optimizations yet -- handling special matrix types would be the next step, after eliminating symmetric eigendecomposition.

**Comment by mateuszbaran** [comment]
I've looked into it today and I don't think it could work, at least the way I imagined opening this PR. There is no easy way to compute (for example) the matrix square root using Cholesky decomposition.
