### ISSUE TITLE
Docs, Lie group actions are non-commutative (i.e. non-symmetric)

### ISSUE THREAD

**Issue by dehann** [JuliaManifolds/Manifolds.jl#520]
Hi, I just want to confirm one line in the docs for `exp_lie`.  I have Lie group actions in general as non-commutative?  
https://github.com/JuliaManifolds/Manifolds.jl/blob/8274392cc6a1c406f7fe83012e2feefb85e58738/src/groups/group.jl#L846

My concern is that the composition operation here is not symmetric in the general case, or I am missing something? 

I have in general that the sum of Lie algebra elements (tangent vectors about group identity in this case**?) are commutative up to the Lie bracket.  As in, Baker-Cambell-Hausdorf ([wiki](https://en.wikipedia.org/wiki/Baker%E2%80%93Campbell%E2%80%93Hausdorff_formula#An_important_lemma) and also [this](https://en.wikipedia.org/wiki/Lie_group%E2%80%93Lie_algebra_correspondence)) formula:
```
exp(X)exp(Y) = exp(Z)
```
where
```
Z = X+Y + 0.5[X,Y] + ...
```

for non-commutative, the Lie bracket `[X,Y]` is non-zero.

----

** separate question on `log` for Group (Lie Algebra diagonals), see
- #521

**Comment by kellertuer** [comment]
Yes, I think that is a typo in general, the last part should be omitted.

**Comment by mateuszbaran** [comment]
See for example 3.5 of this: https://www.sciencedirect.com/topics/mathematics/one-parameter-subgroup , one-parameter subgroups of Lie groups are commutative.

**Comment by mateuszbaran** [comment]
@kellertuer should we make the docs more clear that this is actually correct?

**Comment by kellertuer** [comment]
I think that would be a good idea.

**Comment by dehann** [comment]
> one-parameter subgroups of Lie groups are commutative.

got it thanks. Perhaps just a comment ("for commutative groups")?

**Comment by mateuszbaran** [comment]
What do you mean by "for commutative groups" here? Even if a Lie group isn't commutative, its one-parameter subgroups are commutative.

**Comment by dehann** [comment]
Ah, so this is the key point:
> Even if a Lie group isn't commutative, its one-parameter subgroups are commutative

The docs do state "one parameter subgroup" on scalars `s` and `t`.  I did not know that was sufficient for commutative.  
https://github.com/JuliaManifolds/Manifolds.jl/blob/8274392cc6a1c406f7fe83012e2feefb85e58738/src/groups/group.jl#L840

So this issue then is more about my knowledge gaps than precision.  My suggestion then would be perhaps just add: "Note, even if a Lie group isn't commutative, its one-parameter subgroups are commutative.".
