### ISSUE TITLE
Tangent vectors of SpecialOrthogonal(n), zero diagonals?

### ISSUE THREAD

**Issue by dehann** [JuliaManifolds/Manifolds.jl#521]
This might be a difference in convention, however, I do recall previous versions of Manifolds.jl working this way:

I have that for Lie algebra so(3), notice the zeros on diagonal of tangent vector:
```julia
M = SpecialOrthogonal(3)

omega = [p;q;r]
Wx = hat(M, Identity(M), omega)

[0 -r  q
 r  0 -p
-q p  0]
```

The skew-symmetric (or cross product matrix).  This then has the exponential map:
```julia
RotMat = exp(M, Identity(M), Wx)
#equally
RotMat = exp_lie(M, Wx)
```

Yet current Manifolds.jl does not work this way any more, notice the ones on the diagonal of the tangent vector:
```julia
_Wx_ = hat(M, Identity(M), omega)

[1 -r  q
 r  1 -p
-q p  1]
```

For example the exponential map for Lie algebra to group should for SO(2) here on [Wiki](https://en.wikipedia.org/wiki/Skew-symmetric_matrix) having zeros on diagonal:
![Screenshot from 2022-08-08 19-55-36](https://user-images.githubusercontent.com/6412556/183553660-df25d7a1-f9a0-45e5-9c07-2e59a13d9f91.png)

**Comment by kellertuer** [comment]
I am confused by your example (but also can not run it since I do not know `p,q,r`.

If I try to recreate it and do

```julian
M = SpecialOrthogonal(3)
ω = [0.1, 0.2, 0.3]
hat(M, Identity(M), ω)
```

the result is

```
3×3 Matrix{Float64}:
  0.0  -0.3   0.2
  0.3   0.0  -0.1
 -0.2   0.1   0.0
```

which is a specific case of yours _but_ as it is correct for skew symmetric matrices with zeros on the diagonal.

**Comment by sethaxen** [comment]
And I don't see the diagonal of all ones:

```julia
julia> X = hat(M, Identity(M), ω)
3×3 Matrix{Float64}:
  0.0  -0.3   0.2
  0.3   0.0  -0.1
 -0.2   0.1   0.0

julia> exp_lie(M, X)
3×3 Matrix{Float64}:
  0.935755  -0.283165   0.210192
  0.302933   0.950581  -0.0680313
 -0.18054    0.127335   0.97529
```

**Comment by dehann** [comment]
Okay, that's what i was expecting to see but for some reason did not (?).  I double checked before posting, but let me recheck again to make triple sure.  For tangent vectors on diagonal I'm expecting to see zeros on the diagonal (as you have above).

**Comment by kellertuer** [comment]
For that it is good to have a concrete code example to run that recreates the bug; that‘s why I first  tried to recreate it with such an example. Sometimes software has bugs, for sure, but here, we seem to not have a bug :)
