### ISSUE TITLE
Aggregating documentation in one place

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#528]
I've just seen this package in the new packages feed: https://github.com/JuliaComputing/MultiDocumenter.jl . Maybe it would be nice for users to have all manifold package documentations in one place?

**Comment by kellertuer** [comment]
What would be the advantage of that? We would have just one place running the docs which we would have to trigger?

I do not completely see an advantage, but sure I wanted to do a common landing page for all packages, then we could do one package for the docs, just that I fear it might be quite some work to change that?

**Comment by mateuszbaran** [comment]
The advantage would be that it would be possible to search for any functionality in one place instead of going through separate documentation systems. Such documentation could be linked from an overview page (like in #406) and I think exist parallel to package-specific docs, not instead of them -- if I understand MultiDocumenter.jl. So there would be very little to change, likely only some tweaks to cross-docs links.

**Comment by kellertuer** [comment]
If both would exist, that doubles information, which has two dangerous sides: (1) inconsistencies (2) confused users. SO I would not introduce that parallel to the specific ones but replace the specific ones with this one large one (maybe on an overview site). And the main change would be where manoptjl.org links to ;)

**Comment by kellertuer** [comment]
This is now done at https://juliamanifolds.github.io/ .
