### ISSUE TITLE
Keywords for retractions

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#547]
I mentioned in #545 we could do (fixed) keywords for retractions. My idea is quite short, but I am not sure its efficient (and we could even do that in base. It would be something like

```julia
struct RetractionKeywords <: AbstractRetraction{T<:AbstractRetraction, K}
    retracttion::T
    kwargs::K
end
function retract(M::AbstractManifold, p, X, m::RetractionKeywords)
    retract(M, p, X, m.retracttion; m.kwargs...)
end
function retract!(M::AbstractManifold, q, p, X, m::RetractionKeywords)
    retract!(M, q, p, X, m.retracttion; m.kwargs...)
end
```

and the same for inverse retractions and vector transports. This way one could fix keywords for a retraction within a type. What do you think? Or is this too inefficient?

**Comment by mateuszbaran** [comment]
Performance should be fine but it feels like a bit overcomplicated way to specify retraction options (retraction is represented by an object, but you can add keyword arguments, but if you don't like that you can also use this wrapper...). Though maybe this complexity is needed, I'm not sure at the moment.

**Comment by kellertuer** [comment]
I feel the problem might be that something like the `ProjectionRetraction` (as an example) might have no keywords on Manifold1, a few easy ones on Manifold2 and a complicated set (completely different from the first easy ones) on Manifold3.

Should the ProjectionRetraction now always store all keywords from M2 and M3 even if it called on M1 where no keywords are used?

**Comment by mateuszbaran** [comment]
Yes, good point.

**Comment by kellertuer** [comment]
Should we put this directly into base?
Is the name ok?
The documentation would explain that this can be used to fix `kwargs` for a certain retraction that one wants to use.

**Comment by mateuszbaran** [comment]
Yes, this should be in ManifoldsBase. The name is OK but maybe `RetractionWithKeywords` would be more clear? Or `RetractionAndKeywords`?
