### ISSUE TITLE
Easier interface for gradient conversion

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#559]
I noticed yesterday that it might be complicated to convert a Euclidean gradient to a Riemannian one. The solution I endet up using for a given manifold `M` and a euclidean gradient in the embedding `grad_f_Euclidean` is

```julia
 rpb = Manifolds.RiemannianProjectionBackend(Manifolds.ExplicitEmbeddedBackend(M; gradient=grad_f_Euclidean))
grad_f(M,p) = Manifolds.gradient(M, f, p, rpb)
```

which is a little clumsy. We could introduce a nicer interface for this – I am just not sure whether that should be done here or over in ManifoldDiff.

**Comment by mateuszbaran** [comment]
Well, we definitely need a better interface for that conversion. Something like `egrad2rgrad` but with a better name.

Regarding `ManifoldDiff`, the current structure is that `ManifoldDiff` builds on top of `Manifolds.jl` so it could be better to put that conversion function in `Manifolds.jl`, or maybe even `ManifoldsBase.jl`.

**Comment by kellertuer** [comment]
Ok, that sounds good.

So just to complete the picture, the “conversion” of a euclidean gradient to a Riemannian one is currently the function `gradient` (maybe not the best name), e.g.

https://github.com/JuliaManifolds/Manifolds.jl/blob/b7ae9637b5a6970ed9357fd34861633100344e58/src/differentiation/riemannian_diff.jl#L208-L218

or

https://github.com/JuliaManifolds/Manifolds.jl/blob/b7ae9637b5a6970ed9357fd34861633100344e58/src/manifolds/SymplecticStiefel.jl#L313-L317

and internally I would like to use that for the simpler version here, that is:

Given the function `grad_f_embedding`(for example the Euclidean one)
implement a function (`name_still_to_find(M, grad_f_embedding, p)` ;)) that returns

`grad_f(M,p)`

that evaluates the first function and does the conversion (calls `gradient`).
But for the same as the gradient function does not have the best of names, I do not yet have a good name here.
When we do that here and in Base we could also export it properly (as well as `gradient`), because currently we do not (maybe because we were not done with the naming/ideas?)

**Comment by mateuszbaran** [comment]
Hm, `gradient` is a bit more high-level because it takes the backend. We probably just need
```julia
 function egrad2rgrad(M::AbstractManifold, p, amb_grad) 
     return change_representer(M, EuclideanMetric(), p, project(M, p, amb_grad)) 
 end 
```
which could be easily re-used and extended (SymplecticStiefel should actually add a method to this new function). So we would have
```julia
 function gradient(M::AbstractManifold, f, p, backend::RiemannianProjectionBackend) 
     amb_grad = Manifolds._gradient(f, p, backend.diff_backend) 
     return egrad2rgrad(M, p, amb_grad)
 end 

 function egrad2rgrad(::SymplecticStiefel, p, amb_grad) 
     Q_p = SymplecticMatrix(p, amb_grad) * p 
     return amb_grad * (p' * p) .+ Q_p * (amb_grad' * Q_p) 
 end 
```
and `name_still_to_find` could also just call `egrad2rgrad`.

Exporting `gradient` is a bit risky because there are many other packages that would like to export such function so there would be conflicts.

**Comment by kellertuer** [comment]
The function definition looks nice to me, just that `e` and `r` are not nice in the name – is e the Euclidean or the embedded one (somethimes its both).

And I was maybe thinking of the last parameter being a function not a tangent vector – but for the lower level approach you propose (which is fine I think) tangents are nicer.

I would maybe prefer

```julia
riemannian_gradient(M, p, gradient_embedding; embedding_metric=...)
```

where the `...` could be `default_metric(get_embedding(M))` by default (or a little layer just `EuclidenMetric`). Maybe such a scheme is a little more `Julia`n ?

**Comment by mateuszbaran** [comment]
I think in the lower level it's better to just pass the tangent vector and not a function. `riemannian_gradient(M, p, gradient_embedding; embedding_metric=...)` is fine I think, `default_metric(get_embedding(M))` also makes sense.

**Comment by kellertuer** [comment]
Sure as I said for the lower level tangent vectors are the better idea. It is still easy to introduce the riemannian gradient this way as

```julia
grad_f(M, p) = riemannian_gradient(M, p, grad_f_eucl(p))
``` 

so that is a nice interface. Thanks for the discussion, I think the combined solution of our ideas are a good extension here. Will do that the next days then :)

**Comment by kellertuer** [comment]
Oh, we do not have a `get_metric` function or a `get_default_metric` function for our manifolds. Them I might implement this first with the `EuclideanMetric()` in the keyword until we have that.
