### ISSUE TITLE
Shouldn't `inner` return a real value on complex manifolds (Stiefel)? 

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#566]
In JuliaManifolds/Manopt.jl#197 we noticed that

```julia
using Manifolds
M = Stiefel(3, 2, ℂ)
p = rand(M)
X = rand(M; vector_at=p)
Y = rand(M; vector_at=p)
inner(M, p, X, Y) # is: complex – expected: real
```

this inner product returns a complex number. I would expect an inner product to return a real number, or am I mistaken?

**Comment by kellertuer** [comment]
...or to be more precise _I_ expected (until now) that that would be real and would love a function that provides the real part (if inner per se is not real), e.g. for Armijo

**Comment by mateuszbaran** [comment]
As I understand it, Riemannian manifolds should have real-valued inner product but we can have Hermitian manifolds with complex-valued inner product: https://en.wikipedia.org/wiki/Hermitian_manifold . I'm not sure what complex Stiefel manifold is exactly supposed to be but my guess would be perhaps a Hermitian manifold?

**Comment by sethaxen** [comment]
IIRC, when you define the inner product on a complex manifold to be real, you're effectively declaring that the manifold is real and just the representation is complex. I couldn't find the issues, but some time ago we consciously decided the inner products should be complex and functions that interpret the complex manifold as real (e.g. `angle`) should just use the real part. See e.g. https://github.com/JuliaManifolds/Manifolds.jl/pull/78

**Comment by mateuszbaran** [comment]
I see, then there is no problem in Manifolds.jl and Manopt.jl should take the real part in Armijo linesearch.

**Comment by kellertuer** [comment]
I think we got to the complex one when discussing real basis with complex coefficients? Then I would like to divide the complex inner product from that from the real-valued metric?

To me that currently feels like we have one function (inner) for two things (metric and inner product)?

Adding the real to inner – hm might be quite quite some work to always track that down everywhere. If possible I would prefer a metric-like function?

**Comment by kellertuer** [comment]
> IIRC, when you define the inner product on a complex manifold to be real, you're effectively declaring that the manifold is real and just the representation is complex. 

I do not think so, there is many complex tangent vectors that reduce to a real value in the inner.
I think the decision was, because complex coefficients of real basis vectors were easy that way.

I thought about that on the way home, and I prefer to split the ideas of inner and metric maybe?

**Comment by kellertuer** [comment]
Here is my idea why the metric is the real part (and what's different from the inner product maybe)

Take the complex numbers. `x=a+bi` and `y=c+di` the metric (or inner product on R2) is `<x,y> = real(xy^H) = ac + bd` which is the real part of the inner product (taking the complex conjugate into account. This is for measuring angles and distances, for sure.

If you think in bases, you can take the same inner product as above (or metric) and use `1+0i` and `0+1i` with real coefficients.
_Or_. you use only `1` and __Complex__ coefficients. for those you actually also need the imaginary part of the `imag(x^Hy) = ad - bc` from the thing above, but only there, not for the metric.

One might discuss whether inner is the thing for the bases and its real part - used for the metric – should then get a new name, but I would prefer to have semantically a function for the actual metric, i.e. the first part I started with.

**Comment by kellertuer** [comment]
The thing that might be least breaking is maybe to keep inner/metric as the real thingy and introduce an `inner_complex` for the complex one?

If we go for something breaking then of course we should choose `metric(M, p, X, Y)` and `inner(M, p, X, Y)` where the first would just be the real part of the second (and norm is the sort of metric), and the only thing that is a little bit of work is updating all docs.

**Comment by sethaxen** [comment]
I don't know the right solution here; it's been a while since I thought of this.

> The thing that might be least breaking is maybe to keep inner/metric as the real thingy and introduce an `inner_complex` for the complex one?

Probably not `inner_complex`, since there are also quaternionic manifolds.

**Comment by sethaxen** [comment]
I guess I would be more inclined to have `inner_real`, just like we have `real_dimension`, but then how is that different from `real(inner(M, p, X, Y))` like we have now?

**Comment by kellertuer** [comment]
Hm, yes real_dimension would fit to that...

I think my problem is really more conceptually (so maybe others might have that as well), thinking of inner as the metric/angle/distance-thingy I would expect it to be real.

So I would be more open for an `inner_complex` or `complex_inner` indeed – but sure both your proposal as well as mine are opinion based and more a question what to expect from which function.

**Comment by kellertuer** [comment]
... and if we can not agree on a naming, maybe just doing `metric(M, p, X, Y) = real(inner(M, p, X, Y))` is the easiest solution, that just needs some documentation, but its maybe better to have a function with a clear distinction (that is where one can expect a real value).

**Comment by kellertuer** [comment]
So I thought about this,

maybe the `real(inner(...))` is the easiest solution and we could go with that for now, but if we find a way to help a user avoiding the confusion (that maybe also only I had) that would be nice. I will close this for now and fix Manopt the next days (just have to find the time to track down all inners)

**Comment by mateuszbaran** [comment]
Is this really completed? Maybe it would be a good idea to improve docs a bit to better explain the interface.

**Comment by sethaxen** [comment]
I agree, if it confuses us, it's worth documenting. Maybe with a usage example.

**Comment by kellertuer** [comment]
For real manifolds, I think there is nothing we could extend,

for complex manifolds you have exactly this difference, that

a. For a complex basis of the tangent space _or_ anything angle/distance related from the inner product – we need the real-part of `inner`
b. For a real basis of TpM we need the complex/current one.

I will think about how to maybe extend the docs of `ManifoldsBase.inner` to this extend.
