### ISSUE TITLE
Injectivity radius of a Rotation manifold

### ISSUE THREAD

**Issue by const-ae** [JuliaManifolds/Manifolds.jl#573]
Hi, 

I was looking for the injectivity radius of rotation manifolds.  I found that you are always returning $\pi \sqrt{2}$:
```julia
injectivity_radius(Rotations(10))
> 4.442882938158366
```

Yet, when I played around this seems too tight as a bound. If I plug in a tangent vector with a norm of 5 the `log` of the `exp` still returns the original tangent vector:

```julia
rot = Rotations(5);
poi = random_point(rot);
tang = random_tangent(rot, poi);
norm(tang)
> 1.0
sum((4.5 * tang - log(rot, poi, exp(rot, poi, 4.5 * tang)))^2)
> -1.8797076257219422e-30
```

Does the example make sense? Is that the expected behavior? How /where did you find the injectivity radius for rotation manifolds?

Best, Constantin

**Comment by mateuszbaran** [comment]
Hi!

Great question, that appears to be incorrect. I've found this paper: https://arxiv.org/abs/math/0609627v1 but I haven't checked what scaling needs to be done to match our metric. It would be great to fix this.

**Comment by kellertuer** [comment]
I think it might be me who implemented that wrongly, since in very early stages (when Manifolds where still in Manopt.jl) we already had https://github.com/JuliaManifolds/Manopt.jl/blob/b6fdd47b484ab565a9f6945ba878c403700a116b/src/manifolds/Rotations.jl#L186. We should check for a good reference (Maybe Mateusz one, but I will take a look as well), fix this and document it properly where it's from. Thanks for noticing!

**Comment by kellertuer** [comment]
At least for SO(3) it is π/2, see https://lcvmwww.epfl.ch/publications/data/articles/63/Means_and_Averaging_in_the_Group_of_Rotations.pdf

**Comment by sethaxen** [comment]
The Lie algebra of $\mathrm{SO}(n)$ are the real skew-symmetric matrices $\mathfrak{so}(n)$ . All such matrices $X$ are diagonalizable as $X=U\Lambda U^\mathrm{T}$ with unitary eigenvectors $U$ and pure imaginary eigenvalues $\lambda_i = \pm \mathrm{i} \theta_i$ for real $\theta_i$ (more specifically, the eigenvalues come in conjugate pairs, and for odd $n$ there is at least one eigenvalue of 0). Then the exponential is $p = \operatorname{Exp}(X) = U S U^\mathrm{T}$, where $S_{ij} = \delta_{ij} e^{\lambda_i}$. So the exponential map is invertible using the matrix logarithm whenever $e^{\lambda_i}$ is invertible for all $\lambda_i$. But this is just 2D rotation, so we know the map is invertible if $\theta_i \in (-\pi, \pi]$ for all $i$. 

Lastly, we use the Euclidean inner product, so we have
$$\lVert X \rVert = \sqrt{\langle X, X \rangle} = \sqrt{\sum_{i=1}^n |\lambda_i|^2} = \sqrt{\sum_{i=1}^n \theta_i^2}.$$

The largest value of $\lVert X \rVert$ for which the invertibility condition is just satisfied comes when $|\theta_i| = \pi$ for $n$ values of $\theta_i$ if $n$ is even or $n-1$ values if $n$ is odd. This is $\pi \sqrt{n}$ for even $n$ and $\pi \sqrt{n-1}$ for odd $n$. This is not what we define as the injectivity radius; it provides the upper bound on invertibility of the exponential. This is the one @kellertuer refers to in the old code.

The smallest value of $\lVert X \rVert$ for which the invertibility condition is just satisfied comes when a single conjugate pair has $|\theta_i| = \pi$, which produces a result of $\lVert X \rVert = \pi \sqrt{2}$. This lower bound is the injectivity radius. Note also that many papers use a scaled Euclidean metric for rotations (scaled by 1/2), so they would drop the `sqrt(2)`.

Previously the Rotations code used the correct injectivity radius, but it was changed in #499 and now defaults to the injectivity radius of unitary matrices, which is not the same.

> At least for SO(3) it is π/2, see https://lcvmwww.epfl.ch/publications/data/articles/63/Means_and_Averaging_in_the_Group_of_Rotations.pdf

@kellertuer I think they're talking about the convexity radius, not the injectivity radius, see e.g. http://www.cim.pt/docs/84/pdf#page=125.

**Comment by sethaxen** [comment]
Btw for unitary matrices, it's a similar story, except their eigenvalues don't come in conjugate pairs, so the supremum of all injectivity radii is $\pi \sqrt{n}$, and the infimum is $\pi$, so this could be fixed by just specializing the real general unitary matrices.

**Comment by kellertuer** [comment]
Oh, I was not careful enough there, you are right.

Thanks for the detailed answer, I have two short questions

1. Do you have a reference for your explanations that we could add to the docs?
2. The fix should be relatively easy as you say, because we can dispatch on the field (complex or real) as you way.

But for me it seems there might also be a difference whether we are on the Lie group (SpecialOrthogonal) or not (Rotations), but I could not find much information about the exponential and its infectivity radius for the rotation matrices with the embedding to the sphere (and we also do not have exp/log on Rotations).

**Comment by sethaxen** [comment]
> Do you have a reference for your explanations that we could add to the docs?

No, just what I wrote there. I'll see if I can find one.

> But for me it seems there might also be a difference whether we are on the Lie group (SpecialOrthogonal) or not (Rotations), but I could not find much information about the exponential and its infectivity radius for the rotation matrices with the embedding to the sphere (and we also do not have exp/log on Rotations).

Can you clarify what you mean? `SpecialOrthogonal` is just `Rotations` equipped with multiplication as the group action. With the Euclidean metric, the group exponential and Riemannian exponential are the same (within a composition with the base point, but that's always invertible so has no impact on the injectivity radius). I'm not certain what you mean by the embedding of the rotations in the sphere.

**Comment by kellertuer** [comment]
Ah, I thought they might be different, then all is fine and we can just implement that once for Rotations (and SO(n) will pass down to that).

Yes a reference would be great to help the user. I can do the PR then.

**Comment by sethaxen** [comment]
Oh, and one more note. `SpecialUnitary` is like `Unitary`, except we have the additional constraint that the sum of the eigenvalues is 0. But this again means that our infimum is reached when we have a single pair of nonzero eigenvalues with $\theta_i=\pm \pi$, so the injectivity radius is $\pi \sqrt{2}$. `Orthogonal` is just two copies of `Rotations`, only one of which is reachable by the exponential, so it has the same injecitivity radius.

This all applies to the quaternionic unitary groups as well, so it makes sense to special-case:
```julia
injectivity_radius(::GeneralUnitaryMatrices) = π
injectivity_radius(::GeneralUnitaryMatrices{n,ℝ}) where {n} = π * sqrt(2.0)
injectivity_radius(::GeneralUnitaryMatrices{n,ℝ,DeterminantOneMatrices}) where {n} = π * sqrt(2.0)
injectivity_radius(::GeneralUnitaryMatrices{n,𝔽,DeterminantOneMatrices}) where {n,𝔽} = π * sqrt(2.0)
```

**Comment by kellertuer** [comment]
Nice extension – but isn't the second to last line (real unitary ones) included in the last one (any field F)?

I can add these when I do the PR, sure – will also check whether I find some literature on this.

**Comment by sethaxen** [comment]
> Nice extension – but isn't the second to last line (real unitary ones) included in the last one (any field F)?

Yes, but the 2nd and 4th lines will I believe introduce an ambiguity that needs to be resolved by the 3rd.

**Comment by kellertuer** [comment]
Ah, missed that by thinking too mathematical ;)
