### ISSUE TITLE
`log` on `Stiefel{N, M, ℂ}` leads to ambiguous MethodError

### ISSUE THREAD

**Issue by lukas-weber** [JuliaManifolds/Manifolds.jl#596]
When I try the following
```julia
using Manifolds, LinearAlgebra
M = Stiefel(2, 2, ℂ)
x = ComplexF64[1 0; 0 1]
log(M, x, x)
```
I get
```
ERROR: MethodError: log!(::AbstractManifold, ::Matrix{ComplexF64}, ::Matrix{ComplexF64}, ::Matrix{ComplexF64}) is ambiguous. Candidates:
  log!(M::Hyperbolic, X, p, q) in Manifolds at /mnt/home/lweber/.julia/packages/Manifolds/ClaN0/src/manifolds/HyperbolicHyperboloid.jl:376
  log!(M::AbstractSphere, X, p, q) in Manifolds at /mnt/home/lweber/.julia/packages/Manifolds/ClaN0/src/manifolds/Sphere.jl:331
  log!(::MetricManifold{ℝ, SymmetricPositiveDefinite{N}, LogCholeskyMetric}, X, p, q) where N in Manifolds at /mnt/home/lweber/.julia/packages/Manifolds/ClaN0/src/manifolds/SymmetricPositiveDefiniteLogCholesky.jl:136
  log!(M::MetricManifold{ℝ, <:SymmetricPositiveDefinite, <:GeneralizedBuresWassersteinMetric}, X, p, q) in Manifolds at /mnt/home/lweber/.julia/packages/Manifolds/ClaN0/src/manifolds/SymmetricPositiveDefiniteGeneralizedBuresWasserstein.jl:147
...
```
Doing this with the real version of `Stiefel` works.

**Comment by kellertuer** [comment]
Oh, interesting observation.
This indicates that the method is not implemented. Then our “search for the dispatch on the right log” runs into exactly this error.

Thesis also indicated by

```julia
julia> default_inverse_retraction_method(M)
PolarInverseRetraction()
```
which should usually return `ExponentialRetraction()``when `exp` exists/is implemented.

Why the is interesting is, because the code

https://github.com/JuliaManifolds/Manifolds.jl/blob/73cfc7b77afe853b9195c2561f6bce65117ef600/src/manifolds/StiefelEuclideanMetric.jl#L2-L23

seems to indicate (both in the doc string and the implementation) that this should actually work.
I will try to find some time soon to take a closer look.

A first “workaround” is to use the above recommended inverse retraction (which is a certain first-order approximation to the exponential map usually computationally cheaper) i.e.

```
julia> inverse_retract(M, x, x, PolarInverseRetraction())
2×2 Matrix{ComplexF64}:
 0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im
```

Most of our algorithms and higher-level functions that depend in this have a keyword-argument `inverse_retraction_method=` that defaults to the `default_inverse_retraction_method(M)` mentioned above to exactly “work around” the problem that the log (or the exp similarly) might not be known in close form or be too costly to implement.

But as I said I will check why the existing log – which seems to be the right one for complex as well – is not hit at the moment.

**Comment by mateuszbaran** [comment]
> But as I said I will check why the existing log – which seems to be the right one for complex as well – is not hit at the moment.

The papers our implementation of log on real Stiefel is based on are only concerned with the real Stiefel, not the complex one. So there might be some adjustments needed to make them work for the complex Stiefel manifold.

**Comment by lukas-weber** [comment]
Thanks everyone for the quick response and helpful ideas for workarounds! Manifolds.jl is one of the nicest julia packages I’ve used so far! :)

I encountered this while using Manopt.jl to do some `gradient_descent` on the Stiefel. It is somehow calling log internally, but I haven’t spotted a way to specify the inverse retraction method.

I defined @mateuszbaran’s workaround. I don’t have a special way to test if it’s correct (and limited knowledge about the math) so I tried plugging the result into the exponential map for some random points.

```
julia> M = Stiefel(3,2,ℂ)
Stiefel(3, 2, ℂ)

julia> x = rand(M); y = rand(M)
3×2 Matrix{ComplexF64}:
 -0.551824+0.231997im   0.584629+0.319937im
 -0.192356+0.153347im  -0.069594-0.556212im
 -0.726348+0.231453im  -0.477788-0.115554im

julia> exp(M,x,log(M,x,y))
3×2 Matrix{ComplexF64}:
 -0.551824+0.231997im   0.584629+0.319937im
 -0.192356+0.153347im  -0.069594-0.556212im
 -0.726348+0.231453im  -0.477788-0.115554im
```
Which seemed to work for all points I tried. Manopt seems to be happy with it as well.

**Comment by kellertuer** [comment]
Thanks for our kind words – and that ou are evensong Manopt.jl! Supert!

I think the retraction I proposed should work as well.

I can not give much of a tipp concerning the gradient descent without seeing the call. It should have the `retraction_method` to move forward, but if you for example have a `StopWhenChangeLess` stopping criterion, it uses internally the distance and _that_ by default uses log and norm – there we have the log :) – least that would be my rough guess where that pops up.

**Comment by lukas-weber** [comment]
Manopt.jl is also a real treat to use!

Oh, indeed, I was using that stopping criterion. So that is where it was coming from!

**Comment by kellertuer** [comment]
Thanks!

Well then you could modify that and replace the distance (that has an optical parameter to use a retraction indeed) or change it to use a gradient norm instead.

**Comment by mateuszbaran** [comment]
Thank you, it is really encouraging to hear that you like our libraries :slightly_smiling_face: .

Expanding a bit on Ronny's comment, you can use for example `StopWhenChangeLess(M, 1e-10)` and it will automatically use polar inverse retraction to approximate the distance. For a stopping criterion such approximation should be sufficient (and much faster).

**Comment by kellertuer** [comment]
Oh yes, sometimes I even forget a few “tricks” we already came up with. For a lot of things in Manopt, they have an optional first parameter `M` (for example any debug action, record action or stopping criteria) that does exactly this adaption to specific manifold functions that do or do not exist.

**Comment by kellertuer** [comment]
Hi Lukas,
is this resolved by the way? Then we could close the issue :)

**Comment by mateuszbaran** [comment]
I think ideally we should just implement `log` on that manifold but there are good workarounds for stopping criteria in optimization.

**Comment by kellertuer** [comment]
Do you have a closed form formula for that?

**Comment by mateuszbaran** [comment]
No, and neither the is one for the real Stiefel. We use an optimization-based approach for `log` on the real Stiefel, and similarly we could use something similar for the complex one.

**Comment by kellertuer** [comment]
the other point whether to add log or call it differently is not so much something that should be discussed here I think, but more in a new issue since that might even be breaking for the real case.

Thanks for responding so fast, I think I'll close this for now then.
