### ISSUE TITLE
Documentation on Julia 1.9

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#611]
We need to update Pluto notebooks to quarto to be able to build documentation on Julia 1.9: https://github.com/JuliaManifolds/Manifolds.jl/pull/607#issuecomment-1557603893 .

**Comment by kellertuer** [comment]
Well, to be precise we have to use quarto markdown files instead of Pluto ;)

**Comment by kellertuer** [comment]
I indeed tried to update notebooks, and something between Pluto and PlutoStaticHTML does not work at least on mz side with Pluto 1.9;
I will probably move them to Quarto even before I have figured out how to do Quarto on CI (see https://github.com/JuliaManifolds/Manopt.jl/pull/254, but there is still some things open to be solved).
