### ISSUE TITLE
Improve default `atol` when comparing to 0

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#630]
Currently most places when we compare to 0 with `isapprox` have defaults that cause the comparison to be exact. `KendalShapeSpace` is one exception. I think we should change other defaults (when `isapprox` with 0 happens) to match approximate comparison in `KendalShapeSpace`.

**Comment by kellertuer** [comment]
Could we link here, what we would like to have best? I was hoping to have a bit of time during Christmas to work on a few easier Issues to reduce our number of open ones. This seems to be not-so-hard to do, if we know what we are aiming for.
Or phrased differently – I had thought our approx-checks do follow the default from Julia, so we should check a bit how to change those defaults (maybe even in a non-breaking way)?

**Comment by kellertuer** [comment]
I also would not consider this a breaking change since we basically fix a bug compared to the Julia default.
But if I read that correctly that is really a matter of every single manifold maybe even of every floating point type individually?

**Comment by mateuszbaran** [comment]
Basically, yes. Every `isapprox` check needs to be separately considered to pick the right `atol`.

**Comment by kellertuer** [comment]
uff. So then this is more like an infinite-forever-open issue? I would not even know how to do this on a type-of-values (float64? float32?) basis – and introducing this for every manifold individually sounds also like a larger pile of work.

**Comment by mateuszbaran** [comment]
Well, we have a finite number of comparisons to zero so it can be resolved. It's not even in every manifold. I guess something like `atol=sqrt(prod(representation_size(M)) * eps(T))` should be fine-ish in most cases. At least more fine than the current state.

**Comment by kellertuer** [comment]
We can at least do that as a good fallback. Ah and further – when do we actually compare to zero? Do we check the second argument for being a zero vector (in `isapprox(M, p, X, Y)` check whether X _is equal_ to the zero vector or Y is?) and then I am not sure when this might ever happen for points in `isapprox(M; p, q) `? Maybe only for the special case of Euclidean or the Circle.

Don't get me wrong I am not criticising the idea in general, I am just trying to narrow down what is actually to do :)

**Comment by mateuszbaran** [comment]
No, I'm not even considering generic calls to manifold `isapprox`. I'm just thinking about things like:
```julia
function check_vector(G::SpecialLinear, p, X; kwargs...)
    trX = tr(inverse_translate_diff(G, p, p, X, LeftForwardAction()))
    if !isapprox(trX, 0; kwargs...)
```
or (already adapted)
```julia
function check_vector(M::EmbeddedTorus, p, X; atol=eps(eltype(p)), kwargs...)
    dot_nX = dot(normal_vector(M, p), X)
    if !isapprox(dot_nX, 0; atol, kwargs...)
```
or
```julia
function _isapprox(M::EssentialManifold, p, q; kwargs...)
    return isapprox(distance(M, p, q), 0.0; kwargs...)
end
```
i.e. comparisons where one of the things are hard-coded to zero scalars/vectors/arrays.

**Comment by kellertuer** [comment]
ah, sure there we could add your proposed atol in the inner ones and still pass the `kwargs...` so the user can still adapt them
