### ISSUE TITLE
Consider making RecursiveArrayTools and StaticArrays weak dependencies

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#656]
It might be a bit counter-intuitive to the current structure, where we have these methods with specific manifolds,
but I think for the package it would be neat if these packages that introduce speedups for certain data types would be weak dependencies.

**Comment by kellertuer** [comment]
I will maybe try this next, though for `RecursiveArrayPartition` this might be breaking, since previously we exported `ArrayPartition`.
The rest seems mainly to be reorganising code.

**Comment by mateuszbaran** [comment]
This may indeed be a bit breaking so I'd prefer to have it scheduled for the next breaking release instead of rushing it now.

**Comment by kellertuer** [comment]
I started and noticed it is mainly code-reorganisation, but there might be 2-3 small breaking things

* `ArrayPartition` is reexported and that is no longer the case after this change
*  `we might loose a few default implementations that are no longer available when you “just” load Manifolds (since a random function creates an ArrayPartition for example)

So – I will slowly do this, open a PR, but that should really only be merged when we have more reasons for a breaking change – since this decoupling will also not have such a large effect on loading and such.

So I fully agree with your opinion :)

**Comment by mateuszbaran** [comment]
We can probably close this because RecursiveArrayTools is now a weak dependency and StaticArrays is not worth extracting at the moment?

**Comment by kellertuer** [comment]
Yes.
