### ISSUE TITLE
Please update dep of BoundaryValueDiffEq.jl to v5.

### ISSUE THREAD

**Issue by PhyX-Meow** [JuliaManifolds/Manifolds.jl#664]
This prevents Manifolds.jl to be compatible with latest DifferentialEquations.jl

**Comment by mateuszbaran** [comment]
I would really like to update it but first this issue needs to be resolved: https://github.com/SciML/BoundaryValueDiffEq.jl/issues/117 , or we would have to drop Julia 1.9 (which we won't do until a stable version of Julia 1.10 is released). See #657 , which updates compat entry.

**Comment by kellertuer** [comment]
I do not want to drop support for anything between 1.6 (LTS) and 1.9, that long recompilation time is annoying, though.
But then we have to sadly wait for the linked SciML issue to be resolved.
