### ISSUE TITLE
Possible allocation issue with complex groups?

### ISSUE THREAD

**Issue by olivierverdier** [JuliaManifolds/Manifolds.jl#668]
Consider a complex group, for instance
```julia
G = Unitary(2)
```
Now, the identity element is a matrix of *floats* (probably normal so far?)
```
eltype(identity_element(G)) # Float64
```
The problem is with allocation (I suppose?).
First, this works well:
```julia
eltype(allocate_result(G, typeof(rand))) # ComplexF64
```
But this doesn't:
```julia
eltype(allocate_result(G, typeof(rand), identity_element(G)) # Float64 <-- wrong type?
```
And, what I would perhaps like best, this doesn't either:
```julia
allocate_result(G, typeof(rand), Identity(G)) # BoundsError
```
**Note:** I came across this issue by trying to implement a `rand!` function for complex groups, for testing purposes, and *not* by playing around with `allocate_result`, which, I understand, is for internal use.

**Comment by mateuszbaran** [comment]
Yes, that's something I need to fix. I will do it when I get a bit of free time.

**Comment by mateuszbaran** [comment]
I've prepared a PR with a fix: https://github.com/JuliaManifolds/Manifolds.jl/pull/677 . `allocate_result(G, typeof(rand), Identity(G))` doesn't work but `allocate_result(G, typeof(rand))` does. I can make `allocate_result(G, typeof(rand), Identity(G))` also work but it's a bit more work.

**Comment by olivierverdier** [comment]
Nice! The `Identity` one is really not important, you can just ignore it.
