### ISSUE TITLE
Why does exponential map on the Sphere return points outside of the Sphere?

### ISSUE THREAD

**Issue by Nimrais** [JuliaManifolds/Manifolds.jl#715]
I am using `Manifolds.jl` v0.9.15.

The following is confusing for me

```julia
julia> using Manifolds

julia> sp = Sphere(1)
Sphere(1, ℝ)

julia> p = rand(sp)
2-element Vector{Float64}:
 0.8953358144881157
 0.4453917144434801

julia> exp(sp, p, [1, 0])
2-element Vector{Float64}:
 1.3252229899021544
 0.24064617032837635

julia> norm(exp(sp, p, [1, 0]))
1.3468951526599684
```

What am I doing wrong? I thought that the exponential map should return points that are staying on the manifold.

**Comment by kellertuer** [comment]
To add:
If you take a tangent vector

```
julia> X = [-p[2], p[1]]
2-element Vector{Float64}:
 -0.4453917144434801
  0.8953358144881157

julia> is_vector(Sphere(1), p, X, true, true)
true
```

you also get
```
julia> q = exp(Sphere(1), p, X)
2-element Vector{Float64}:
 0.10896780051622529
 0.9940452798794712

julia> is_point(Sphere(1), q)
true
```

**Comment by Nimrais** [comment]
Ahh, yes thanks for the fast answer, I see the issue now!

**Comment by kellertuer** [comment]
Great :) We specifically provided the two functions `is_point` and `is_vector` to help a bit with checks.

On the other hand we do not always check all input. You can activate that (to narrow down an error for example) by wrapping your manifold in a `ValidationManifold` https://juliamanifolds.github.io/ManifoldsBase.jl/stable/manifolds/#A-manifold-for-validation, that actually calls the above two functions on inputs and results within most functions of `Manifolds.jl`
