### ISSUE TITLE
Add `check_point` for complex `SymplecticStiefel`

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#735]
The existing one only works for real numbers.

**Comment by kellertuer** [comment]
Can you maybe provide an example? I just did

```
julia> M = SymplecticStiefel(4,2,ℂ)
SymplecticStiefel(4, 2; field=ℂ)

julia> p = rand(M)
4×2 Matrix{ComplexF64}:
 -0.998498+0.0im   -1.6602+0.0im
 -0.609752+0.0im  -1.18466+0.0im
  -2.05232+0.0im  -4.49237+0.0im
  0.820544+0.0im    1.7227+0.0im

julia> is_point(M,p)
true
```

If I assume that `rand` us correct, the point check also works just fine?

**Comment by mateuszbaran** [comment]
Does it actually return `false` for incorrect points? See here: https://github.com/JuliaManifolds/Manifolds.jl/blob/732ab727f995ce0ccc3ce4bf994c33cabd28cbdb/src/manifolds/SymplecticStiefel.jl#L113 . It most likely hits some default implementation that only checks the embedding.

I noticed it when checking this ambiguity:
```julia
check_point(M::SymplecticStiefel{<:Any, ℝ}, p; kwargs...) @ Manifolds ~/.julia/dev/Manifolds/src/manifolds/SymplecticStiefel.jl:113
check_point(M::SymplecticStiefel, p::StiefelPoint; kwargs...) @ Manifolds ~/.julia/dev/ManifoldsBase/src/point_vector_fallbacks.jl:119
```

**Comment by kellertuer** [comment]
right, that I did not check, I thought it was failing somwhere. You are right then it probably just checks the embedding, i.e. field type and dimensions for now.

but p^+p just has to be checked on complex as well then. I can check whether I see how much to do that is (maybe even just removing R)

**Comment by kellertuer** [comment]
Hm, I checked a bit the code. First of all, the complex part (also of p above) is zero, so I am not sure we can generate (non real) symplectic matrices. So I am also not sure what to actually additionally check.

To conclude, I would consider this not fully installed, but also not much I can do here (neither good-first nor easy to extend) since I am not aware of Literature that could help us here.

**Comment by kellertuer** [comment]
It seems `canonical_project` is wrong as well for complex ones – but I think again we should mainly further restrict those then, because I am not much aware of complex symplectic Stiefel literature.

**Comment by mateuszbaran** [comment]
I see, I didn't really check how difficult that would be to add because it looked quite simple but maybe it isn't actually.

**Comment by kellertuer** [comment]
I think the problem is that the main idea of the model here is to cover real-valued things; maybe I was too optimistic adding the complex case to the manifold at all. For example the paper is also only called the real-valued symplectic Stiefel.
So it might be better to remove the complex case here.

**Comment by kellertuer** [comment]
Baby the best is then to remove the complex case (we have a breaking PR open anyways) also for symplectic Grassmann?

I could not find any literature on the complex case

**Comment by mateuszbaran** [comment]
I think it would be enough to limit signatures of methods that don't work in the complex case.

**Comment by kellertuer** [comment]
But that is the current case already. Then the complex case falls back to our optimistic check-default that returns nothing.

**Comment by mateuszbaran** [comment]
Ah, right, then maybe let's indeed limit symplectic Stiefel and Grassmann to real numbers for now.

**Comment by kellertuer** [comment]
Great. On the 0.10 PR? Could you add that or shall I?

**Comment by mateuszbaran** [comment]
I will do that on the 0.10 PR.
