### ISSUE TITLE
solve_exp_ode has wrong function signature in docs

### ISSUE THREAD

**Issue by r0uv3n** [JuliaManifolds/Manifolds.jl#740]
In https://github.com/JuliaManifolds/Manifolds.jl/blob/e31e7b088b402af19741ef3b300eccc850d96edc/src/manifolds/ConnectionManifold.jl#L374, the doc definition disagrees with the definition in e.g. https://github.com/JuliaManifolds/Manifolds.jl/blob/e31e7b088b402af19741ef3b300eccc850d96edc/ext/ManifoldsOrdinaryDiffEqExt.jl#L31: It should be
```julia
solve_exp_ode(
        M::ConnectionManifold,
        p,
        X,
        t::Number;
        B::AbstractBasis,
        backend::AbstractDiffBackend = default_differential_backend(),
        solver = AutoVern9(Rodas5()),
        kwargs...,
    )
``` 
instead of
```julia
solve_exp_ode(
        M::ConnectionManifold,
        p,
        X,
        t::Number,
        B::AbstractBasis;
        backend::AbstractDiffBackend = default_differential_backend(),
        solver = AutoVern9(Rodas5()),
        kwargs...,
    )
```

**Comment by r0uv3n** [comment]
I'll try to submit a PR to fix this and a few other issues related to solve_exp_ode sometime today.

**Comment by kellertuer** [comment]
Nice, thanks for spotting this. It seems we indeed moved the basis to a keyword argument (or designed it as positional but imlpemented it keyword).

Yes, if you could do a PR for this and other typos you find, we are always grateful for anyone helping us improving code and docs :)
