### ISSUE TITLE
`solve_exp_ode` does not ever update position

### ISSUE THREAD

**Issue by r0uv3n** [JuliaManifolds/Manifolds.jl#744]
`solve_exp_ode` seems to always return the starting point `p` for any input. See e.g.
```julia 
using Manifolds
using OrdinaryDiffEq
E = Euclidean(3)
p = [0, 0, 0] # point in E
A = get_default_atlas(E)
i = Manifolds.get_chart_index(E, A, p)
B = Manifolds.induced_basis(E, A, i, TangentSpaceType())
X = [0, 0, 1] # tangent vector
time = 1

Manifolds.solve_exp_ode(E, p, X, time; basis=B)
```
which returns `[0, 0, 0]` (i.e. just the starting point `p`).

**Comment by r0uv3n** [comment]
This seems to be due to a very typo where in https://github.com/JuliaManifolds/Manifolds.jl/blob/af95b030b54ef8d511a680741992a68d89bde616/ext/ManifoldsOrdinaryDiffEqExt.jl#L64 the first element instead of the last element of the solution `u` is accessed.

**Comment by kellertuer** [comment]
If you see how this can be fixed, feel free to also open a PR for this. Otherwise, probably Mateusz will step in, he I´might just be a bit busy currently, maybe.

**Comment by mateuszbaran** [comment]
Right, sorry for the mistake, I will fix that this weekend.
