### ISSUE TITLE
Computations related to frames

### ISSUE THREAD

**Issue by AdrienAngeAndre** [JuliaManifolds/Manifolds.jl#769]
I am implementing similar methods to Lie-group methods and I wanted to use the Manifolds.jl package to have a manifold independent implementation. Given any point $p$ on a Riemannian manifold, I need to generate a local orthonormal frame $(E_d)$ around $p$ (for instance, with parallel transport). Then, I need to compute the quantity $\sum_{d=0}^D \nabla_{E_d} E_d$, with $\nabla$ the Levi-Civita connection. A sufficiently accurate approximation could maybe be sufficient. Is it possible to implement this conveniently with Manifolds.jl?

An additional difficulty (which comes second in the order of priority) is that the neighbourhood of p on which the local frame is defined should not vary too much in size by changing the point p. For instance, I cannot have the standard frame defined by spherical coordinates on the sphere, as the neighbourhood decreases a lot in size when p is near the poles (and the Lipschitz constant of the $E_d$ blows up).

**Comment by mateuszbaran** [comment]
This sounds like something best done in charts. We have some basic support for them in Manifolds.jl, see here for an example: https://juliamanifolds.github.io/Manifolds.jl/stable/tutorials/working-in-charts/ and I'd be happy to improve it if you need something more. There is `affine_connection` you can use with an example implementation on `EmbeddedTorus`. I've already worked out chart switching and integration with the DIffEq ecosystem.

So far I haven't seen a convincing chart-free approach to such computations.

**Comment by kellertuer** [comment]
If you have a paper or any numerics related information how that could be done, we are happy to help get that going.I am just not aware of any.

**Comment by olivierverdier** [comment]
@AdrienAngeAndre If the manifold is embedded in $`{R}^n`$ and if the metric is the pull-back metric, then you might be able to work without charts (by projecting a convenient basis of $`R^n`$ to the manifold and using automatic differentiation)

For maximum generality, you should work with charts but, as far as I can see, `Manifolds.jl` will not help you much, other than computing the curvature/connection tensors you need in a given basis (which is already nice, of course!).

Either way, that's quite an extensive project, in my opinion.
